### ISSUE TITLE
G1 - Expected breadcrumb formats for News, FAQ, Events, Services, and Pages

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#113]
**News**
Listing Pages: Home / News
Detail Pages: Home / News / News Category

**Events**
Listing Pages: Home / Events
Detail Pages: Home / Events / Event Category

**Page**
Detail Pages: Home / Category

**FAQ**
Listing Pages: Home / FAQ
Detail Pages: Home / FAQ / FAQ Category

**Services**
Listing Pages: Home / Services
Detail Pages: Home / Services / Service Category

**Comment by mmafe** [comment]
**Example for CCS Service Updates:**

(URL: /ccs/events/service-updates/)
Listing Page: Home / Events

(URL: /ccs/events/service-updates/name-of-service)
Detail Page: Home / Events / Services Updates

**Comment by brharp** [comment]
Partially completed. Only breadcrumbs based on content type have been implemented.

**Comment by brharp** [comment]
Removed the breadcrumb for services (they will go in the menu.)

**Comment by mmafe** [comment]
Breadcrumbs based on content type are no longer showing - see https://github.com/brharp/hjckrrh/issues/172

**Possible reasons:** I've tried checking out earlier copies of the repository and so far, none of the node pages are showing the breadcrumb (even though they were showing the breadcrumb last week). The only difference between this week and last week is that we updated Drupal core and ctools.

**Comment by mmafe** [comment]
**Confirmed reason:** The security upgrade from ctools v 1.7 to ctools v 1.8 is causing the breadcrumbs to disappear. None of our code has changed, so I'm guessing the update to ctools is somehow overriding (or changing the behaviour of) the hook we're using to override the breadcrumbs.

**Possible solutions:** Security fix is a must, so we'll either need to update the hook to make it work or use a different hook.

**Comment by mmafe** [comment]
**Update:** So it looks like if we include a "Node: Content" pane (with No Extras checked), the hook gets triggered and we see the breadcrumb again.

Looking into this further. So far, the following issue trail appears to relate:
https://www.drupal.org/node/1606912
https://www.drupal.org/node/1760384
https://www.drupal.org/node/2422123

**Comment by mmafe** [comment]
@brharp had a good idea for where we might go next with breadcrumbs: https://www.drupal.org/project/taxonomy_breadcrumb

**Comment by mmafe** [comment]
**Update:** Hansel module is looking promising and also allows for taxonomy-based rules.

For future reference on configuring Hansel:
http://cgit.drupalcode.org/hansel/tree/README.txt?id=refs/heads;id2=master

**Comment by mmafe** [comment]
**Update:** Hansel is not playing nicely with multiple sites when the vocabulary ids differ. Currently investigating the Crumbs module.

**Comment by abanuog** [comment]
installed easy_breadcrumbs module, and set up default URL patterns for news, events, services, and faqs. Need to create a new feature with these settings.

**Comment by mmafe** [comment]
**Github triage meeting suggestion:** Revisit the idea of using the ug_theme_node_view_alter(&$build) hook to insert the content type reference into the breadcrumb.

**Comment by abanuog** [comment]
After much trial and error, trying drupal hooks and various contrib modules, the module path_breadcrumbs seems to be a good solution. It allows Drupal to continue using regular breadcrumbs for items in the menu, and custom breadcrumbs for items such as News, Events, etc. that are not in the menu. Need to configure a few more rules, and do more testing.

**Comment by mmafe** [comment]
Note: if multiple categories can be selected, we may not be able to include the category on the detail page of each content type.
