### ISSUE TITLE
G6 - Global Nav Dropdowns are hidden after opening toggle menu, shrinking to narrow and then moving to wide view

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#115]
Global navbar has issue where if you shrink the viewport to a narrow view (i.e. phone-size), open the dropdown toggle and then widen the viewport to a wide view (e.g. 768 px or above), the dropdown menus are hidden behind the orange bar.

They only appear if you tab through the global nav menu to Academics or About and use the up and down arrow keys to navigate through the dropdown menus, however, the display appears broken (i.e the navbar shifts down and you can see the hidden dropdown menu.)

It does not appear to be happening on the u of guelph homepage.

![image](https://cloud.githubusercontent.com/assets/1927902/9018233/d279f5d6-37aa-11e5-8377-16ab093e0912.png)

(Note: I was originally fixing a display issue that occurred with the global nav when you shrink to narrow and move to wide view. Since the two issues overlap, I've commented out the css code for the display issue so we can tackle one issue at a time.)

**Comment by mmafe** [comment]
**Update on issue:** The hidden dropdowns issue does not seem to be occurring anymore.

However, we are still seeing the grey display issue on both our theme and the uoguelph.ca homepage.

**Comment by mancusop** [comment]
Created new issue  https://github.com/ccswbs/hjckrrh/issues/348 For theming bug,

**Comment by mancusop** [comment]
Hasn't this issue been resolved as per Mirandas comment above?

**Comment by ushenoyuog** [comment]
Closing this issue as the initial bug seems to be resolved. Also a new issue is created for the grey display, so this is duplicate. For all theming issues we will await the new theme.
