### ISSUE TITLE
G4/G6 - Expand/Collapse state is not immediately announced by Chrome with NVDA (Works in FF/NVDA)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#166]
This is just a summary of findings related to aria-expanded toggle behaviour in Chrome/NVDA.

Currently the aria-expanded "expand/collapse" state is not being announced immediately after you press a (Bootstrap coded) expand/collapse toggle button in Chrome with NVDA.  Instead, we have to leave the element and then focus back onto the element (e.g. tab off and then tab back onto it again) in order to hear the state of aria-expanded. In Firefox with NVDA, we hear the expand/collapse announcements as expected.

**Current Situation**
The following examples do not work in Chrome/NVDA, but they do work in FF/NVDA:
https://dev.web.uoguelph.ca/aodademo/toggles
http://getbootstrap.com/javascript/#collapse

**For Future Reference**
We've found a few examples (using aria-expanded) which work with NVDA in both Chrome and Firefox:
http://heydonworks.com/practical_aria_examples/ (go down to #3 - Progressive Toggles)
http://oaa-accessibility.org/example/22/

If we can figure out the difference between the two scenarios, we can fix the issue (eventually).

**Comment by mmafe** [comment]
Interesting article regarding on how browsers, screen-readers, and aria interact: http://www.ssbbartgroup.com/blog/how-browsers-interact-with-screen-readers-and-where-aria-fits-in-the-mix/

It sounds like no matter what we do, we're going to find different support for aria on different screen-reader/browser combinations.

**Comment by mancusop** [comment]
As an update, issue is still present in our current sprint

**Comment by ushenoyuog** [comment]
This issue seems to have been fixed. tested on history of business page on chrome and NVDA.
