### ISSUE TITLE
E6 - Find Related Events view is inconsistent with other Find Related News/FAQ, etc. views

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#167]
E6 - Find Related Events view is inconsistent with other Find Related News/FAQ, etc. views.

Should be a comma-delimited list. Update view to match other views.

**Comment by ushenoyuog** [comment]
This is probabaly a super quick fix, so bumping it up into the backlog to be done. 

## News 

![image](https://cloud.githubusercontent.com/assets/23462414/24523584/8198d0c4-1561-11e7-9988-ab9ba6426a15.png)

##  Events

![image](https://cloud.githubusercontent.com/assets/23462414/24523617/9b55f582-1561-11e7-9475-584a1d19cf2b.png)

**Comment by ushenoyuog** [comment]
##  Acceptance Criteria

1) Check to see if any other "Find related content type by " needed to be updated. 
2) E6- find related events by keyword is updated.
