### ISSUE TITLE
G3 Local Search - change 'search'  term

### ISSUE THREAD

**Issue by Dmelady** [ccswbs/hjckrrh#170]
Sites have commented that for clarification between local and UofG search they would like to indicate their site name ie? Arts or Search Arts in the local Search box. 
![image](https://cloud.githubusercontent.com/assets/13487599/9410564/f8a2383c-47ee-11e5-93eb-8b6589592b66.png)

**Comment by mmafe** [comment]
This issue is related to: https://github.com/brharp/hjckrrh/issues/204

**Comment by ushenoyuog** [comment]
This seems to have been fixed. closing issue.
![image](https://cloud.githubusercontent.com/assets/23462414/25011839/b5c3440c-203c-11e7-8cc8-26ff28d2b9e1.png)
