### ISSUE TITLE
All Teaser views- Configure View options for new Website Manager role

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#173]
- Number of items to show should be configurable
- Don't show 'Link Title to View' option
- Option to show only certain categories in the view.

**Comment by mmafe** [comment]
Additional requests:
- Allow site manager to override the specific text that appears after the more button (e.g. More News by default, but they can override "News" to be "Featured News")

**Comment by ushenoyuog** [comment]
All of these options seem to have been completed. Closing issue. 

![image](https://cloud.githubusercontent.com/assets/23462414/25012138/9328fa08-203d-11e7-8eb1-fc8bc8640d86.png)
