### ISSUE TITLE
N1 - News listing URL shows different page # than pagination

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#176]
**Issue first seen by @Dmelady:** I believe this might be associated or incorporated into this ticket. If not we can separate. In clicking on the pagination # (say page 2) the URL reflects '/news?page=1'... could be somewhat confusing to the webuser? 
![image](https://cloud.githubusercontent.com/assets/13487599/9394338/e9a391ee-4755-11e5-95c2-4e1220e28f7f.png)

Also affects: Events, FAQ, Services, any any other listings with pagination

**Comment by nevantan** [comment]
This is a non-issue.
