### ISSUE TITLE
G0 - Ensure that revisions are turned on for all content types in platform

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#180]
Ensure that revisions is turned on for all content types in platform

**Comment by ushenoyuog** [comment]
Verified that revisions is turned on for page, news, book.

Not available for events, people profiles, banners, features

To check FAQ and services.

**Comment by nevantan** [comment]
Potentially solved by #431 and #649.

**Comment by mmafe** [comment]
Verified that under Default options, "Create new revision" is turned on for:
- page
- news
- book

"Create new revision" needs to be turned on by default for:
- [ ] events
- [ ] people profiles
- [ ] banners
- [ ] features
- [ ] course outlines
- [ ] faq
- [ ] services
