### ISSUE TITLE
E9b - Drupal errors when an event is scheduled

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#186]
Whenever you are viewing a week that has an event scheduled, Drupal spits out a bunch of errors at the top of the screen. 

https://aoda.web.uoguelph.ca/aodademo/events/week/grid?week=2015-W28
https://aoda.web.uoguelph.ca/aodademo/events/week/grid?week=2015-W35

![week error 2](https://cloud.githubusercontent.com/assets/12450480/9586445/f48d7334-4fea-11e5-9070-53a1c464d25d.PNG)

![week errors](https://cloud.githubusercontent.com/assets/12450480/9586569/9b77f840-4feb-11e5-86f0-1eb667e812f4.PNG)

**Comment by mmafe** [comment]
Known drupal issue: https://www.drupal.org/node/2160183

Investigating the proposed solutions.

**Comment by mmafe** [comment]
Further info: Only occurs when nodes occur on a single day (not multi-date)

**Comment by mmafe** [comment]
For the time being, if you see this happening on a live site, do the following:

1. Go to your Calendar View.
2. Choose the Week Display.
3. Click on Settings in Format: Calendar | Settings .
4. You'll see Time Grouping, with the dropdown set to Hour.
5. You don't need to change anything, but click Apply (this display).
6. Then don't forget to click Save on the View editing page.
7. Now go to the Week view for your calendar. The error should be gone.

Once grid view starts being used on the production sites, we'll prioritise on adding a fix to the platform.

**Comment by ushenoyuog** [comment]
This issue doesnt seem to be happening any more . closing for now . We can reopen if needed.
