### ISSUE TITLE
G0 - File attachment icon alt text can be improved

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#191]
The alt text for the file attachment icons can be greatly improved. Some of the alt text is overtly long and none are formatted in a very screen-reader-friendly manner (e.g. the icon for the docx extension comes through as "application/vnd.openxmlformats-officedocument.wordprocessingml.document"). It would be nice if they were just something like "pdf", "zip", "docx", etc.

@mmafe stated in issue #159: "At a glance, it looks like the file module we're using appears to only have access to the mimetype when generating the icon."

![attachment alt](https://cloud.githubusercontent.com/assets/12450480/9604652/ea7f9d80-5086-11e5-916c-45a71d72bc44.PNG)

**Comment by brharp** [comment]
Created new branch issue191 .

**Comment by jpinsent** [comment]
This issue appears to have been resolved.
![alt text fix](https://cloud.githubusercontent.com/assets/12450480/11691010/2763518c-9e67-11e5-860c-a9be47f5e781.PNG)
