### ISSUE TITLE
E9a/E8a - Large gap between text and image

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#192]
The 'This Week' and 'This Month' listing pages have a large empty gap between the image and the text, which is inconsistent with the views for upcoming and past events.

This is continued from issue #183.

![this week](https://cloud.githubusercontent.com/assets/12450480/9605225/7033ec3a-508a-11e5-8009-6fc7b84fe5d6.PNG)

![5c471fc6-4be4-11e5-9e66-9eeceb4ba310](https://cloud.githubusercontent.com/assets/12450480/9605236/857238d6-508a-11e5-9aff-f5d4850eb136.PNG)

**Comment by ushenoyuog** [comment]
This doesnt seem lik its happening anymore. Closing issue for now. Can be repoened if needed. 
![image](https://cloud.githubusercontent.com/assets/23462414/24524637/58f489e8-1565-11e7-902a-868f607cf63a.png)
