### ISSUE TITLE
G0 - Keyword delimiter not specified

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#20]
When filling out the keyword, the comma delimiter used to separate multiple keywords is not specified anywhere on the page. There are no instructions for the user to know how to properly format multiple keywords in the form.

**Comment by brharp** [comment]
Added help text to page keywords.

**Comment by jpinsent** [comment]
The help text seems to only appear under the Keywords field for basic pages. Banner, News, FAQ, Feature, Service and Events are still missing help text for their Keywords fields.

**Comment by JProxxi** [comment]
Help text for keyword delimiters is still not present for: Banner, Event, Feature, and Profile.

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#20 - Keyword delimiter not specified](https://trello.com/c/jJMxNEzh/239-20-keyword-delimiter-not-specified)

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#20 - Keyword delimiter not specified](https://trello.com/c/jJMxNEzh/239-20-keyword-delimiter-not-specified)

**Comment by ushenoyuog** [comment]
Seems to be closed
