### ISSUE TITLE
S3 - No link to social media directory

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#202]
The spec states: 

```
If more than 8 social media accounts are created, the last button becomes a "Social Media Directory"
```

At the moment, it only displays 8 icons with no way to access the rest.

**Comment by mmafe** [comment]
**Update:** Social Media Directory has been pushed to next iteration development. Spec has been updated to convey this. For now, let's leave the issue open, but we'll be switch the label to enhancement request

**Comment by ushenoyuog** [comment]
This issue has existed for a while, but we have yet to come across an actual client site that has more then 8 icons. So closing this issue for the moment as it is unlikely to ever become a priority. If this becomes an issue on an actual site
