### ISSUE TITLE
S5 - No icon present

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#206]
The spec states: 

![twitter view 2](https://cloud.githubusercontent.com/assets/12450480/9765762/d93d11c0-56e3-11e5-985d-dd926eb10142.PNG)
```
1. **Icon for Social Media Type:** Icon most relevant to the type of social media being displayed (e.g. Twitter bird logo, Facebook logo, RSS Feed icon, etc.)
```

This is the view I'm seeing on every website:
![twitter view](https://cloud.githubusercontent.com/assets/12450480/9765758/d278cc30-56e3-11e5-908a-c10e0cefc89c.PNG)

I'm not seeing a social media type icon.

**Comment by mmafe** [comment]
Spec is out of date. Software works as expected. Issue is no longer required.
