### ISSUE TITLE
G0 - Skip Link takes you to www.uoguelph.ca in Chrome when NVDA is open and in focus mode

### ISSUE THREAD

**Issue by enichol** [ccswbs/hjckrrh#218]
Steps to reproduce issue:
1) Navigate to any page that has the 'Skip to main content' link in Google Chrome.
2) NVDA is open
3) Using tab controls (this sets NVDA to 'focus' mode) navigate to 'GryphMail' and then back to 'Skip to main content' link and hit enter.

Rather than jump to the main content on the current page, the link takes you to www.uoguelph.ca.

**Comment by mmafe** [comment]
Will test.

**Comment by mmafe** [comment]
Tested this item in Chrome and NVDA on the OAC and Childcare sites.

The issue appears to be fixed.
