### ISSUE TITLE
G0 - Helper text for "File Attachments"

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#22]
Help text below the file attachments should say something about how to link a document in-line in the body. Something like:

"to link attachment in text, copy the link address and make a link"

Or something like that, as long as it says "copy link address" and "attachment link" I think the users would understand.

**Comment by mancusop** [comment]
@mmafe This is only seems to pertain to the **Basic Page** where when a file is attached, even if the `display` check box is ticked no links to the actual files are displayed on the page and thus must be manually added to the body using the above method.

However in both **Events** and **News** this is not the case as when the `display` checkbox is ticked the created page will automatically show the list of files uploaded to the content type.

Is this the correct behavior?

**Comment by JProxxi** [comment]
This Issue has been resolved
