### ISSUE TITLE
G0 - 'Toggle Navigation' hidden button causes styling issues

### ISSUE THREAD

**Issue by enichol** [ccswbs/hjckrrh#221]
If you disable styling on any page, there is a 'Toggle Navigation button that becomes visible. Clicking it toggles something that causes styling issues when styling is re-enabled (most of the time, depending on how you disable the styling)

**Comment by jpinsent** [comment]
After a discussion with @mmafe, this appears to be a non-issue. The 'Toggle Navigation' button is hidden unless styling is disabled, and there does not appear to be any way to have it interfere with the page while styling is enabled without using the WAVE toolbar.

@mmafe has said she would look into this briefly, so I'll leave this open until she responds.
