### ISSUE TITLE
G6 - "Research" link read as "Researchat" by Chrome/NVDA

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#227]
The screen reader reads the 'Research' link in the global nav as "Researchat University of Guelph". There needs to be a space between 'Research' and 'at'. This only occurs with NVDA in Google Chrome. NVDA in Firefox reads it properly.

This issue is related to issue #157.

**Comment by ushenoyuog** [comment]
Seems to be fixed now.
