### ISSUE TITLE
S1 - Error sharing a page with Linkedin

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#230]
Sharing a page via Facebook and Twitter seem to work fine, but I'm getting an error when I try to share a page via Linkedin. The error message is as follows:

```
We’re sorry. Something unexpected happened and your request could not be completed. Please close this window and try again.
```

![linkedin error](https://cloud.githubusercontent.com/assets/12450480/10167911/7a5b84ec-6698-11e5-8b63-7ecf270b1f03.PNG)

**Comment by abanuog** [comment]
Seems to work, but needs confirmation.

**Comment by abanuog** [comment]
Had to modify the linkedin share link, to set the url field correctly.
