### ISSUE TITLE
BK2 - Navigation links don't indicate relationships to previous/next pages to screen readers

### ISSUE THREAD

**Issue by enichol** [ccswbs/hjckrrh#233]
When going through book pages on a screen reader, the navigation links to go forward/back/up a page only indicate the name of the link, and not the relationship of the linked page to the current page.

**Comment by mmafe** [comment]
**Note:** Title attribute is being used by the module to convey the previous, next, up information. However, this is not a great technique, so I'm leaving the issue open in case we try and improve this in future.

**Comment by mmafe** [comment]
Link text now conveys the name of the next and previous pages. Screen-reader only text conveys the relationship (eg. Next, Previous, etc.) just prior to the link text.

Considering this fixed.

![book-iss233](https://cloud.githubusercontent.com/assets/1927902/24372220/3ea6c0ea-12fb-11e7-9565-ab8f29efce26.png)
