### ISSUE TITLE
S5 - Twitter feed markup error

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#237]
Running a page with the Twitter feed present produces the following markup validation error:

```
Error: Duplicate attribute class.
```

https://validator.w3.org/nu/?showsource=yes&useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&doc=https%3A%2F%2Fwww.uoguelph.ca%2Foac%2F

**Comment by jpinsent** [comment]
It looks like this issue magically fixed itself; the markup issue has vanished.

I'll move this down to a lower priority and leave this issue open for a week just in case the error springs back up.

**Comment by jpinsent** [comment]
UPDATE: The issue has returned. It seems like it's caused whenever a tweet mentions another user with the "@" notation.

```
 <p class="media-summary">RT <a target="_blank" rel="nofollow" class="twitter-timeline-link" href="http://twitter.com/IntelSec_Home" class="twitter-timeline-atreply">@IntelSec_Home</a>: Don't get starstruck. Watch where you click. <a href="http://t.co/0CNnnCQFM2">http://t.co/0CNnnCQFM2</a> #RiskyCeleb <a href="http://t.co/J61lC7xesW">http://t.co/J61lC7xesW</a></p>
```

**Comment by mmafe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) #237 Twitter feed markup error](https://trello.com/c/Cof8Ugz6/2025-5-237-twitter-feed-markup-error)

**Comment by ushenoyuog** [comment]
![image](https://cloud.githubusercontent.com/assets/23462414/22349454/bf6922e2-e3dd-11e6-8c69-e0424f3887e1.png)
![image](https://cloud.githubusercontent.com/assets/23462414/22349462/cb899476-e3dd-11e6-88fb-9b519802cc26.png)

Acceptability Criteria

- Pages with Twitter feeds , where feed includes mentions (@name) should validate.

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Twitter Feed Validation Error](https://trello.com/c/VwcFMIXr/232-twitter-feed-validation-error)

**Comment by nevantan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#237 - Twitter Feed Validation Error](https://trello.com/c/q3iLbtLN/2119-237-twitter-feed-validation-error)

**Comment by ushenoyuog** [comment]
Closing issue as it seems to be merged

**Comment by nevantan** [comment]
@brharp updated the RPM with the Twitter patch, so it should go out in the next release. We will need to run [MCB](https://aoda.client.uoguelph.ca/mcb/) and [Food Science](https://aoda.client.uoguelph.ca/foodscience/) through the validator again when the patch goes out.

**Comment by ushenoyuog** [comment]
Was released on Apr 6th 2017. Checked and confirm the feed validates now.

**Comment by bdavey07** [comment]
Checked client version of MCB and Food Science, validates, live version of MCB also validates
