### ISSUE TITLE
FT3 - Listing page is not filtered

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#238]
As an admin, it is possible to change the category by which a featured list teaser is filtered. When you go to "More features" on the filtered view, however, it takes you to a listing page of all features (unfiltered). 

The Trello card states the following under functional tests:  

```
Navigate to the appropiate https://trello.com/c/o1GiTtaa/149-ft2-listing-page-for-featured-item from this view, dependent on the current category (e.g. if teaser list is filtered by "videos", then the resulting listing page of features should also be filtered by "videos"
```

**Comment by mmafe** [comment]
For testing, branch is issue238

**Comment by enichol** [comment]
After finally successfully re-making the site on the testing machine, the issue appears to be fixed.
