### ISSUE TITLE
SR3 - Listing page not sorted alphabetically unless overridden

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#240]
The spec for SR3 states that it should be sorted alphabetically. On the [AODA Demo](https://aoda.web.uoguelph.ca/aodademo/service-category/computer-printer-and-server-support), the SR3 listing page is sorted by post date. On the [CCS](https://www.uoguelph.ca/ccs/category/service-category/computer-printer-and-server-support), it appears to be overridden to be sorted alphabetically by title.

This can be seen in the view for Taxonomy term (Content). The sort criteria on AODA Demo includes 'Content: Post date (desc)' whereas the sort criteria on the CCS includes 'Content: Title (asc)'.

**Comment by ushenoyuog** [comment]
Tested out SR3 ,SR1 and SR 8 on a fresh sit. This seems to be fixed.
![image](https://cloud.githubusercontent.com/assets/23462414/25022514/24ff307a-2064-11e7-838c-9b5d8f164815.png)
![image](https://cloud.githubusercontent.com/assets/23462414/25022523/2db75562-2064-11e7-9e5a-2ab3ddde8775.png)
