### ISSUE TITLE
R1-Add Manager role

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#248]
Requirements defined in Trello card- G00

**Comment by enichol** [comment]
Views tested:
B1 - Image slider
E1 - Listing page for multiple events
E3 - Upcoming events
E8 - Monthly Calendar
E9 - Weekly Calendar
FT1 - Feature item
FT2 - List of featured item
FT3 - Featured item teaser list
N1 - List of news articles
N3 - Recent news teaser list
S3 - Follow us icons
S4 - Follow us icons & names

All look good.
