### ISSUE TITLE
E6 - Find related events by keyword not underlined

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#250]
Seen on Grad Studies: https://www.uoguelph.ca/graduatestudies/node/336

Links in body content are always underlined. Links under 'Event Website' and 'Events Archive' do not have an underline under them unless rolled over. Links in 'Find related events by keyword' are never underlined.

Requires further investigation. Suspect that 'Find related events by keyword' feature is incomplete

**Comment by ushenoyuog** [comment]
This happens on all sites . Should be fixed. 
![image](https://cloud.githubusercontent.com/assets/23462414/24525117/1717f472-1567-11e7-9f45-e55fd4917367.png)

So far this seems to be the only place this is happening, but perhaps some additional investigation would be nice.

**Comment by nevantan** [comment]
Look at this issue for consistency. See News keywords for reference.

**Comment by nevantan** [comment]
Fixed by #718.
