### ISSUE TITLE
R1- Ensure Manager role only has ability to edit page layouts without overriding feature.

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#251]

**Comment by jpinsent** [comment]
Site Managers **can** customize the layout on the following:

- [News listing](https://aoda.web.uoguelph.ca/aodademo/news)
- [Events listing](https://aoda.web.uoguelph.ca/aodademo/events)
- [Events detail pages](https://aoda.web.uoguelph.ca/aodademo/esca-ex-ratis-sit) 
- [FAQs](https://aoda.web.uoguelph.ca/aodademo/faq)
- [Services listing](https://aoda.web.uoguelph.ca/aodademo/services)
- [Services detail pages](https://aoda.web.uoguelph.ca/aodademo/abluo-blandit-haero-utrum) 
- [News detail pages](https://aoda.web.uoguelph.ca/aodademo/test-1-0)
- [Features listing](https://aoda.web.uoguelph.ca/aodademo/features)

Site Managers **cannot** customize the layout on the following:
- [Basic page detail pages](https://aoda.web.uoguelph.ca/aodademo/page-sample)
- [FAQ questions](https://aoda.web.uoguelph.ca/aodademo/faq/faq-1/abico-eligo-molior)
- [Service category](https://aoda.web.uoguelph.ca/aodademo/service-audience/future-students)

@mmafe stated that detail pages for basic pages should be customizable. Not sure about the rest. Removing fixed label for now.

**Comment by jpinsent** [comment]
It looks like UG Page Layout was overridden, which was preventing the panels-in-place editor from working. We reverted the Page Layout on AODA Demo and it seems to be working now.

All of the above features' layouts can be changed by the site manager without overriding the feature.
