### ISSUE TITLE
R1- Ensure Manager role only has ability to edit categories (taxonomy) for all features without overriding feature.

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#252]

**Comment by brharp** [comment]
On a fresh, default install, the editor, etc. do not have permission to edit vocabularies. Is it possible that the example we looked at last Friday was not in the default state? Does anyone remember which site we were looking at?

**Comment by mmafe** [comment]
I don't remember the example we looked at, but I can confirm on my local site install (fresh) that editor, etc. do not have the permission to edit vocabularies.

**Comment by jpinsent** [comment]
Looks like site manager is the only one who can edit taxonomy. They can edit, add or delete any terms. They can only change the format to Plain Text or Basic HTML. They are not able to edit descriptions using Full HTML.

This issue has been resolved.
