### ISSUE TITLE
R1- Ensure Manager role (only) has ability to choose Category option on all views listing content (teasers/lists) without overriding feature

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#253]

**Comment by enichol** [comment]
All lists and teasers checked. Few issues:
<b>N1 - News Listing</b> - 'Category' field in the in-place-editor label is displaying as  "Content: Category (field_news_tags)", which is inconsistent with the other views. 
<b>E1 - Events Listing</b> - Category field does not appear for either site manager or wbsadmin.

**Comment by anncesar** [comment]
There is still a problem with News Teaser list not showing category option for site manager in customize this page.

**Comment by mmafe** [comment]
@brharp @abanuog Hey Joy and Brent, would it be possible to include a category option filter for the news teaser list before the May 17th release? Since we're going to be using news as our go-to-feature for any articles that require listing by date, we'll need to be able to filter by category.

**Comment by brharp** [comment]
Fixed in 7.3.0
