### ISSUE TITLE
Ensure Manager role (only) can assign other roles ('lower' status roles only)

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#258]

**Comment by enichol** [comment]
Currently, I don't think there's any way to test this. When logged in with a Site Manager, you can't access the 'People' tab on the Drupal menu, and I don't know of any other way to change user roles.

**Comment by mmafe** [comment]
Hey @brharp, it looks like Site Manager is unable to access user profiles to change the roles. Do we need to add further permissions in order to do this?

**Comment by mmafe** [comment]
**Notes from discussion with @brharp:** This will likely need Role Delegation and Restrict Password in order to work. Permissions then can be configured to allow Site Managers to edit user role.

**Comment by brharp** [comment]
Fixed in 7.5.0
