### ISSUE TITLE
R1- Ensure Manager role can change 'More' label for teasers to match title.

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#259]
Or, if the label included the title automatically- such as 'More "Title'''

**Comment by enichol** [comment]
Manager can currently change the 'More' button text for News Teaser Lists, however all other teaser lists seem to be unable to change. Checked on SR8 - Services Teaser, E3 - Events Teaser, FT3 - Feature Teaser. This may simply be an issue with overrides.

**Comment by mmafe** [comment]
@abanuog Talk to @brharp about this. News teaser list has the ability we're looking for,  but we need to add to the rest of the teaser lists.

**Comment by brharp** [comment]
Merged with develop.

**Comment by brharp** [comment]
@abanuog Still missing for service teaser (SR8)?

**Comment by abanuog** [comment]
SR8 is a view of service categories, and shows all items by default. A "more" link is therefore not necessary.
