### ISSUE TITLE
R1- Ensure Manager role (only) can edit Footer/Header

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#260]

**Comment by enichol** [comment]
Permissions seem to be correct; Only site manager can edit the footer. Currently there is no 'Header' panel to test, but in the event one is added the permissions will be identical to the footer, as they will both be implemented as mini-panels.

**Comment by mmafe** [comment]
@brharp Hey Brent, is there a reason that site managers are unable to administer mini-panels? Is the expectation that we will add the mini-panel for them and then they'll be able to edit the mini-panel?
