### ISSUE TITLE
(C) Ability for users to add custom content that appears in different areas of the page and on different pages.  

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#261]
Feature requirement- as per developed specification- Trello card #207

**Comment by anncesar** [comment]
Decided to defer until next release:
- workaround will be 1) override page layout and add item 2) allow users to add to sidebar (preferred method). 
- PJ should ensure this is included in training.

**Comment by abanuog** [comment]
No longer required. We are using blocks and allowing users to override the layout.
