### ISSUE TITLE
G- Create Feeds for all views that are consumeable by anonymous user

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#262]

**Comment by mmafe** [comment]
Confirmed as completed on E1 (events listing) and N1 (news listing). Thanks @abanuog

**Comment by mmafe** [comment]
After demo feedback, we are going to be meeting to review how feeds can be incorporated into the front-end of some of the views we have available. More information can be added to this issue so we know specifically which features should have feeds, as well as which feeds will provide access to the feed URL.
