### ISSUE TITLE
G- Establish default front page layouts for pages

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#263]
This should be specified (documented requirements)- see Trello card- G14-#240
https://trello.com/c/ZkCKfdnw

**Comment by mmafe** [comment]
We're thinking 2 types of default layouts for the front page. One for academic units and one for administrative (more service-oriented) units.

#Academic
- 3 column layout
- news, features, events

#Administrative
- 3 columns layout
- services, events, FAQ

In both cases, search can be added via mini-panels if they'd like to see that.

**Comment by abanuog** [comment]
Talked with Brent about this, and it seems that most people have been creating custom front page
layouts, so this is probably not needed anymore.
