### ISSUE TITLE
BR1- Ability to use banner categories to display different banners on different sections/pages of site.

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#264]

**Comment by brharp** [comment]
This can be achieved with the existing views and mini-panels. For example, to create a "services" banner:

- Add term "Services" to the "Banner category" vocabulary.
- Assign one or more banners to the "Services" category.
- Create a mini-panel "Services banner".
- Add one of the banner views (B1 - Image slider) to the mini-panel
- Select category "Services"
- Assign block "Mini panel: Services banner" to the Top Bar region
- Configure visibility settings for the block (e.g. show only on the page "services")

Note that this configuration could also replace the blocks explicitly exported by the ug_banner feature (reducing the number of views overall).
