### ISSUE TITLE
N3- Ability to choose to include Summary in News Teaser list view.

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#266]

**Comment by anncesar** [comment]
@mmafe should I be able to see this on my sandbox?  thx.

**Comment by mmafe** [comment]
@anncesar Nope - there are no pull requests associated with it.

I'm pretty sure this work has not been done by anyone on the AODA Remediation team. @brharp or @abanuog, if you've done work on this (issue266), please let me know and I can merge the branch with the sprint demo branch.

**Comment by mmafe** [comment]
This issue appears to have been fixed - new pane is showing up.
