### ISSUE TITLE
G0 - Anchors (Including skip to main content) don't work in Chrome

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#27]
Anchors (#name) don't work in chrome. You have to right click on the link and open in a new tab and it will work fine. This is odd, as anchors work fine in the old template but not in the new one.

EG. https://www.uoguelph.ca/ccs/security/protect-your-pc-guide works
https://aoda.web.uoguelph.ca/ccs/node/288 doesn't work

The new template does work in firefox though. Something with Chrome isn't working with the new template.

**Comment by JProxxi** [comment]
This issue has been resolved
