### ISSUE TITLE
G- Ensure that all Views have a fall back for dealing with no content

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#270]

**Comment by mmafe** [comment]
Hey @mmatthews, this would just entail going through all the lviews in the platform and ensuring that they all have no results behaviour if there are no results.

Listing views should say "No results found."

Detail views should not collapse (either you should just see a blank page with a sidebar, OR "No results found.")

**Comment by mmafe** [comment]
Hey @abanuog, could you please assist with the following changes on the no results behaviour of the following views. Realized after looking on staging that there were a few views that ended up with odd behaviour (e.g. Event Archives showing "No Results found" in a scenario where it simply should not show.) I've gone through all the views and put together a list of proposed changes.

See below:

- E2b Event multipart: Remove no results behaviour completely.
- E5: Remove no results behaviour completely.
- E6: Remove no results behaviour completely.
- E8a: Change text to "No results found."
- E8b: Change text to "No results found."
- E9a: Change text to "No results found."
- E9b: Change text to "No results found."
- FT2: Add "No results found." to No Results behaviour
- FT3: Add "No results found." to No Results behaviour
- G10: Remove no results behaviour completely.
- N2: Change "no details found" to blank
- N5: Remove no results behaviour completely.
- N6: Remove no results behaviour completely.
- N7: Remove no results behaviour completely.
- P1: Add "No results found." to No Results behaviour
- PG1: Remove no results behaviour completely.
- S1: Remove no results behaviour completely.
- S3: Remove no results behaviour completely.
- S4: Remove no results behaviour completely.
- S5: Add "No results found." to No Results behaviour
- S5 Twitter: Add "No results found." to No Results behaviour
- Taxonomy term: Add "No results found." to No Results behaviour

Thank you!

**Comment by mmafe** [comment]
![image](https://cloud.githubusercontent.com/assets/1927902/13114154/3ae2bc18-d560-11e5-8f0f-3e6a0a505810.png)

Some views are showing a more link even when there are no results found. Please fix so that more link does not show if there are no results.

**Comment by brharp** [comment]
@mmafe e8b and e9b have the correct 'no results behavior' defined, but the calendar grid style doesn't appear to use it. Would you like us to try to find a way to make the calendar grid style display the no results text, or leave an empty grid as the 'no results' behavior for these views?

**Comment by brharp** [comment]
@abanuog View G10 - request was to remove no results completely, but the view has empty no results text defined. Is this intentional?

**Comment by mmafe** [comment]
@brharp Empty grid would be more consistent with the view. The drawback is that anyone with a screen-reader would not have a quick way of knowing the grid is empty, so if there's a way for you to do the empty grid, but include some screen-reader available text that communicates that the grid is empty quickly, that would be ideal.

**Comment by brharp** [comment]
There is an open issue against the Calendar module regarding "no results" behavior: [How to make "no results" work?](https://www.drupal.org/node/2489146)
