### ISSUE TITLE
G0, PG2 - Any page which  adds an existing node as a panel generates an empty h2 with a link.

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#272]
An empty h2 (linked) title is being generated by the node.tpl.php file. This affects any site that adds an existing node as a panel on their pages.

**Steps necessary to demonstrate issue:**
1. Go to any panel page (Admin > Structure > Pages)
2. Add a panel to any region (e.g. middle)
3. Select "Existing content" and add any node
4. Leave all checkmarks unchecked and select "Full content" build mode.
4. Save the panel page.
5. Inspect the added panel. You'll see an extra (empty) h2 title tag with a link inside, but no text. This causes accessibility issues (i.e. a link with no descriptive text)

Code Sample:
 `
 <div class="pane-content">
    <div id="node-181" class="node node-page clearfix" about="/psychology/graduate/cpade/about" typeof="foaf:Document">
        <h2><a href="/psychology/graduate/cpade/about"></a></h2>
    <span property="dc:title" content="" class="rdf-meta element-hidden"></span>
  <div class="content">
`

**Suggested fix:** Override node.tpl.php using our ug_theme folder. Add an if statement that checks if the title variable has a value before printing out the h2 with the link.

See https://www-stage.uoguelph.ca/psychology/graduate/cpade for an example. @tqureshi-uog can point us to more examples of this as well.

**Comment by mmafe** [comment]
More examples from @tqureshi-uog:

Examples of pages where the error occurs:

https://www.uoguelph.ca/psychology/graduate/cpade - search source code for the following:
'<h2>
<a href="/psychology/graduate/cpade/about"></a>
</h2>'

https://www.uoguelph.ca/psychology/graduate/ios - search source code for the following: 
'<h2>
<a href="/psychology/i-o-area-application-deadline"></a>
</h2>'

https://www.uoguelph.ca/ccs/infosec/resources - search source code for the following:
'<h2>
<a href="/ccs/node/1660"></a>
</h2>'

These empty h2 and anchor tags are generated automatically by Drupal's node template when you create a custom panel page and then add content from existing nodes. Even if you uncheck the "Leave node title" option, Drupal will still insert an h2 and anchor tag for that node title.

**Comment by mmafe** [comment]
Pushed branch issue272 to github. Ready for testing.

**Comment by jpinsent** [comment]
It looks like this issue has been resolved. The empty h2 link doesn't seem to be appearing on the page anymore. All links and h2s have associated text.
