### ISSUE TITLE
G4/G6 - Expanded menu in narrow view is skipped over by NVDA in Chrome

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#280]
When using NVDA with Chrome, if you expand either the local or global menu and then attempt to navigate down to them using the arrows keys, the screen reader will skip right over the entire menu structure. You can tab to the menu, which the screen reader will sometimes pick up and other times not say anything.

Not sure what the issue is, since it works fine in Firefox. May be related to https://github.com/ccswbs/hjckrrh/issues/166?

**Comment by jpinsent** [comment]
UPDATE: The local menu on the live sites seems to be picked up by NVDA in Chrome, but not on the AODA Demo site. The global menu is being skipped over on all sites.

Can someone test this on their machine and see if they come across the issue as well? @mmafe @enichol

**Comment by mmafe** [comment]
See https://github.com/ccswbs/hjckrrh/issues/273
