### ISSUE TITLE
PG4 - Empty listing page is blank

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#282]
Empty page listings filtered by keyword are blank when they should say "No results found."

![empty listing page](https://cloud.githubusercontent.com/assets/12450480/11598771/d6c5a37a-9a91-11e5-94ce-97683a917ab0.PNG)

@mmafe Surprise!!!

**Comment by mmafe** [comment]
@jpinsent I would never have guessed. ;)

**Comment by mmafe** [comment]
Updated the branch. Listing page should now say "No results found."

**Comment by enichol** [comment]
Tested out on local machine, looks good.
