### ISSUE TITLE
N1/E1/E15 - No results found spacing is too close together in narrow view

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#283]
When there are no news articles and the browser is in narrow view, News Archive is not spaced from the body content.

![news no results](https://cloud.githubusercontent.com/assets/12450480/11599255/bf34ebec-9a93-11e5-96ce-bb70bf1285c7.PNG)

**Comment by ushenoyuog** [comment]
Doesnt seem to be happening anymore . Closing issue
