### ISSUE TITLE
E0 - Sections Field ambiguous - Discussion 

### ISSUE THREAD

**Issue by mancusop** [ccswbs/hjckrrh#285]
**Discussion:** in AODADEMO, sections field is defined and used as either "Cost" or "Contact Information". Should sections definition and their role be incorporated and discussed via training or should event creation be changed to have already predefined data elements? 

**Thoughts**
- "Cost" element wouldn't / shouldn't need access to a full body rich text editor.
- Same with Contact Information - all that would be needed is email, name, phone #

**Comment by ushenoyuog** [comment]
This may not be relevant any longer. Closing issue for now.
