### ISSUE TITLE
FT0 - Featured Item summary should be 255 chars max

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#298]
For some reason, it looks like Featured Item summaries aren't being shortened as per spec:

![features bug](https://cloud.githubusercontent.com/assets/12450480/11728260/d998d58a-9f56-11e5-907f-e710e2ef2bfb.PNG)

![features bug 2](https://cloud.githubusercontent.com/assets/12450480/11728263/dcd20de8-9f56-11e5-8024-871beab5e7b0.PNG)

- **Summary:** 255 characters. Rich text editing. If no summary, use the first 255 characters of the body field and end with an ellipsis (…). If possible, avoid ending in the middle of a word.

https://trello.com/c/tLf8zwoc

**Comment by mmafe** [comment]
This is no longer considered to be a missing requirement. Clients can be informed of a recommended character limit.
