### ISSUE TITLE
N5b - Replace month/year list with select control

### ISSUE THREAD

**Issue by brharp** [ccswbs/hjckrrh#299]
The list of month/year in the browse news by date view is too long. Replace this list of links with a select list and "go" button.

**Comment by jpinsent** [comment]
Tested & appears to be working in branch 'issue299'.

![news archive dropdown](https://cloud.githubusercontent.com/assets/12450480/11749403/93941cfc-9ffb-11e5-805a-cb7713df65b6.PNG)

**Comment by mmafe** [comment]
Could we remove the number of associated nodes from the list? It could be confusing to hear December 2015 54 on a screenreader without any context on what that number means.

**Comment by mancusop** [comment]
As FYI I did testing for this back in Febuary. JSON report located here:
https://trello.com/c/MjnMHfxJ/21-n5b-browse-news-by-date-select-menu

**Comment by abanuog** [comment]
fixed by brent already.
