### ISSUE TITLE
N3, E3, FT3 - RSS feed to be added to the front-end of each template.

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#311]
We'd like to see an RSS feed on the front-end.
- news teaser list
- events teaser list

Could be placed beside the more link or beside the title.

Related to iss #262

**Comment by anncesar** [comment]
@mmafe @brharp  I'm not sure why this is assigned to me- I think it's fairly straightforward- it's basically adding an RSS feed button to the teaser lists mentioned above.  I'll assign to Brent to do, but feel free to assign someone else.  Brent, I think you already created the feeds- just need to create the front-end buttons on the teaser list views.

**Comment by ushenoyuog** [comment]
Not sure what has transpired since he last discussion here but all three views N3 , E3 and FT3 have the RSS feed available.  So closing this issue... 

![image](https://cloud.githubusercontent.com/assets/23462414/24566096/1d97439c-1626-11e7-839c-40f6e364d9fc.png)
