### ISSUE TITLE
FT3, N3, E3, PG3, F3 (all teaser lists) - When there are no results, more link still shows up

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#324]
![features-more-link-no-results](https://cloud.githubusercontent.com/assets/1927902/12660466/e36d22bc-c5e1-11e5-8275-b269e936f757.png)

So far, seen on featured item teaser list.

**Comment by ushenoyuog** [comment]
Looks like this has been resolved . The more link doesnt show up anymore on the teaser lists when there are no results. 

![image](https://cloud.githubusercontent.com/assets/23462414/24566195/8a0fc094-1626-11e7-901e-b08121deb041.png)
