### ISSUE TITLE
E3 - When filtered by category, ensure the more link goes to an events listing page filtered by category

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#328]
When E3 is filtered by category, the more link still goes to the unfiltered destination page. 

Note: If E3 is showing only upcoming events, then it will need to link to /events/upcoming/category/%category (which will need to be created under Pages).

- [ ] Add events listing page filtered by category (e.g. /events/upcoming/category/%category)
- [ ] Update more link so it links to category when E3 is filtered by category

**Comment by abanuog** [comment]
using the existing /events/upcoming/ page, and adding the term id at the end of the url (eg. /events/upcoming/25 )
