### ISSUE TITLE
G0 -  Current Site Time for Date Fields

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#35]
Switch all time fields to "site wide" time instead of "UTC"

**Comment by jpinsent** [comment]
If you go to Structure > Content Types > Event > Manage Fields and then edit the Date field, you should see the following at the bottom of the page:
![time zone handling](https://cloud.githubusercontent.com/assets/12450480/11510120/fba40c22-982f-11e5-9cae-f5b7e9a07bbf.PNG)

The time zone seems to be set to UTC by default across all sites. UTC time is 6 hours ahead of EST, so this is technically incorrect. I don't think it caused a major issue except that when Joe and I were migrating events from the OAC, we migrated them under the site's time zone. Half way through migration, the Time zone handling switched to UTC and changed all the event times.

I must note that if we change the time zone from UTC to site wide now, it will push the times on all events back by 5 hours. If we change it now, we'd have to make sure to preserve the currently published events' times on the live websites.

**Comment by JProxxi** [comment]
80% certain that this issue is no longer relevant

**Comment by abanuog** [comment]
Checked two sites in production, and they both are using UTC still.

**Comment by mmafe** [comment]
Has this been checked on a fresh install of the UG profile? It's possible that sites in production are overriding events, so I would also confirm if the a fresh install is using UTC as well.

**Comment by abanuog** [comment]
We will change the setting to use "Site Time zone":
 Site's time zone - When entering data into the field, the data entered is assumed to be in the site's time zone. When the data is saved to the database, it is converted to UTC. When retrieved from the database, the data is converted to the Site's time zone for anonymous users or the User's time zone for logged in users when User-configurable time zones is enabled.

**Comment by abanuog** [comment]
has been fixed (moved to production).
