### ISSUE TITLE
R1 - Author permissions - Author content is automaticlly published when saved, Author can't set it to unpublished.

### ISSUE THREAD

**Issue by mancusop** [ccswbs/hjckrrh#366]
Author cannot control if content is published or unpublished. Default setting is all content is published automatically once it is saved. This effects the hiarchy of permissions and makes clients want to only have editors (since they can unpublish their own content or others).

Clients would prefer one of the following enhancements:

1. Default save function leaves content as UNPUBLISHED and Editors can go in and publish the content once reviewed.
2. Have authors given the ability to publish/unpublish their own content.

Assigned Brent to this issue as I didn't know who else to assign it too. I consider this a big issue because it undermines the reason to have authors since their content will always be published without either a) oversight or b) without the ability to unpublish faulty content.

**Comment by Samana04** [comment]
5 clients have requested the ability to have two different permissions as authors:
1. Authors' ability to publish content
&
2. Authors' ability to only save content.

**Comment by mmafe** [comment]
**Solution proposed by Github Triage Meeting:**

- On site-by-site basis, we can change the setting to unpublished by default.
- Editors can also create unpublished content for authors to work on.
