### ISSUE TITLE
UG Theme - Disable Bootstrap CDN as part of default site setup

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#369]
Platform sites are created with Bootstrap CDN enabled and set to version 3.0.2.

This stops the javascript from working, which in turn means the dropdown menus do not work until we manually disable the Bootstrap CDN. 

Instead of us having to do this manually, please set the Bootstrap CDN to "" in the UG Theme strongarm settings, and if possible, export with the UG Theme feature so it's part of the default site setup.

![image](https://cloud.githubusercontent.com/assets/1927902/13673746/7b784c76-e6a8-11e5-85c5-c41a2c882273.png)

**Comment by mmafe** [comment]
**Note:** Until this is fixed, all sites will have to have UG Theme overridden. Raising priority to high.

**Comment by brharp** [comment]
Fixed in 7.2.0
