### ISSUE TITLE
SR0 - Related Services too long on editor

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#37]
I added ~50 dummy services to the AODA Demo site (same as current CCS site), and the content editor now displays all 50 of them at the bottom. (see picture). This is different to how the old services content editor displays them, but still better in my opinion.

What would be good to change would be to display the check boxes in a scroll-able list (see second attached picture). This would make for less scrolling.

Also, currently they are sorted by post date, oldest at the top. It would make more sense to be alphabetically like the old Services Content Type.

![related services](https://cloud.githubusercontent.com/assets/12450523/8115820/0fc9c1ea-104c-11e5-9682-1d880c11c475.PNG)

![scrolling check box](https://cloud.githubusercontent.com/assets/12450523/8115822/16a826e6-104c-11e5-86d0-7c0a8ee71384.PNG)

**Comment by JProxxi** [comment]
More a suggestion than an issue, can be closed in my opinion.
