### ISSUE TITLE
SR0 - Field Headings being required is misleading

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#38]
Both public and private headings (listed under Service Details and Internal Notes respectively) are marked with an asterisk indicating that they are required. They are, however, only required if body content is entered in the field underneath. A page can be published without selecting a heading as long as there is no body content associated with it. This could be misleading to a user, as the asterisk implies that headings must be selected in order to publish the page.

The spec states that, "Once a private/public content heading has been added, an affiliated Private/Public Service Field Description field is made available to the editor." This implies that the content field would be disabled unless a heading is selected, which would eliminate the need to label a heading as being required.

**Comment by brharp** [comment]
Every section requires a heading. The user is not required to add any particular number of sections.

I believe the line you quote from the spec means that once a heading has been added to the vocabulary, it becomes available as a service heading. It is not describing dependent fields on the service entry form.

I don't see any way around this, as the heading *is* required.

**Comment by jpinsent** [comment]
I see. That does makes sense. My apologies; I misinterpreted the spec.

I think that the asterisk may still be misleading to users though, since it does not directly imply that a section can be left blank. Maybe we could add instructions next to the section indicating that the heading may be left blank if no content is entered.

Thanks for clearing that up. I'll change this to a low priority enhancement request.

**Comment by JProxxi** [comment]
seeing as this was just and "enhancement request" and it hasn't been touched in almost a year, it is probably safe to close the issue.
