### ISSUE TITLE
SR2 - Edit, Add, Delete; buttons for the internal notes

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#39]
![service page](https://cloud.githubusercontent.com/assets/12450523/8117278/e3745dd6-1054-11e5-81f2-e230ed4936e5.PNG)

Not too sure if these are suppose to be here

**Comment by mmafe** [comment]
**Ideal Situation:** Remove Edit/Delete/Add, as well as the Heading/Content labels. Also throw styling if time permits.

**Comment by abanuog** [comment]
These links are only there when logged in, to edit content on the page.
