### ISSUE TITLE
P3, E3, N3, FT3 - Style RSS feed icon on teaser lists

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#394]
Suggest styling the RSS feed to match homepage.

Option A - We keep the same larger buttons that we have, but instead we add the RSS feed to the right side of the button. Grey icon.

Option B - We right align the RSS feed button (separate button) and use grey icon for the colour.

http://www.uoguelph.ca/

![more-news-sample](https://cloud.githubusercontent.com/assets/1927902/14211869/583616dc-f7fe-11e5-862a-4c067956257e.png)

**Comment by chyatt** [comment]
I know this is nothing more than a visual annoyance, and arguably not high priority. But it is a bit of an eyesore, and we have heard complaints. What's our appetite for prioritizing this?

**Comment by abanuog** [comment]
This code works for creating the new links:
=================================
<div class="more-link btn-group">
  <a href="/hr/news" class="btn btn-default">More news</a>
  <a href="/hr/news/feed" class="btn btn-default fa fa-rss">
  </a>
</div>
