### ISSUE TITLE
PP2 - Detail page shows image and office fields even if there is no content

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#395]
Detail page shows image and office fields even if there is no content.

![people](https://cloud.githubusercontent.com/assets/1927902/14216180/7afb28bc-f815-11e5-8984-60a3d36bc9e7.png)

**Comment by brharp** [comment]
This may have been fixed, please verify and fix if necessary.

**Comment by ushenoyuog** [comment]
The fields do not show up anymore 
![image](https://cloud.githubusercontent.com/assets/23462414/24677283/41b7ce64-1954-11e7-8113-87405c472124.png)

The space for the image is still present ojn the left, but maybe this is not something that needs fixing. Closing the issue for the moment and will be returned to and reopened if needed.
