### ISSUE TITLE
G0- If you press the "save" button more than once on new content, it duplicates the pages.

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#40]
For example, I was making a service page called "g" and I pressed the save button maybe 10 times. It also happens if you double click the save button, eg the "test" and "tedt" pages.

This happens with all content types.

![duplicate nodes](https://cloud.githubusercontent.com/assets/12450523/8117445/1ec48fe0-1056-11e5-9ef3-0ad171361224.PNG)

**Comment by brharp** [comment]
This is an issue with Drupal core, not with our install profile. Not saying it shouldn't be fixed, but I won't be fixing as part of this project.

**Comment by brharp** [comment]
Will try the [hide_submit](https://www.drupal.org/project/hide_submit) module.

**Comment by brharp** [comment]
Fixed in 7.5.0
