### ISSUE TITLE
G6 - Global navigation "Student Housing Services" link under Services needs update + GryphLife link (with icon)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#401]
Student Housing Services link under Services should point to housing.uoguelph.ca (not www.housing.uoguelph.ca).

![image](https://cloud.githubusercontent.com/assets/1927902/14387282/b8c64620-fd76-11e5-8814-35a25fbac790.png)

---

**Update:** Gryphlife menu item is also different.
![image](https://cloud.githubusercontent.com/assets/1927902/14387274/ac4785a8-fd76-11e5-9930-a0febf40152f.png)

**Comment by brharp** [comment]
Same issue on the U of G home page.
