### ISSUE TITLE
BR1 - Responsitivity bug; image fails to load while scaling at the same time

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#41]
While the banner is playing, if you scale the page while the banner is in the process of changing to the next image, the image fails to load. Not a major issue, since the next image will load as long as you are not scaling the screen at the same time. This is an issue in both Chrome and Firefox.

![responsive bug](https://cloud.githubusercontent.com/assets/12450480/8133656/a2895d96-10f7-11e5-806f-c4d39fb47c18.png)

**Comment by abanuog** [comment]
Doesn't seem to be an issue anymore.
