### ISSUE TITLE
Recommend removing pane-title styling on panel-panel bottom pane

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#437]
Recommend removing the following style from ug-2015 styles:

.panel-panel.bottom .pane-title{
    font-size: 1.286em;
    font-weight: 400;
}

It causes the pane-title on the bottom section to be smaller than all the rest. It was originally added during the 4 early adopted sites, but it is too general and causing issues now where an h2 ends up looking smaller than the other h2s on the page, simply because it's in the bottom panel.

If no clients are using this, recommend removing this style.

**Comment by brharp** [comment]
Fixed in 7.4.0
