### ISSUE TITLE
S1 - Responsiveness error - "share this page" overlapping content

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#45]
![social media responsiveness](https://cloud.githubusercontent.com/assets/12450523/8214639/93925f40-14f8-11e5-9097-adb833fff70e.PNG)

https://aoda.web.uoguelph.ca/aodademo/test-pageeeeeeeeeee

At full screen, the "share this page" block is overlapping this large picture.

**Comment by brharp** [comment]
The alternative would be to clip content or scroll, which I don't think would be any better.
