### ISSUE TITLE
G0 - Can't view content on un-published pages

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#46]
No matter what role you are, if a page is unpublished you can not see the content on the page, only the title. VS the current CCS site, where if you have permission you can view the unpublished page, and non--auth'd uses get a 403 error.

**Comment by jpinsent** [comment]
This issue appears to have been resolved. Editors and admins can see any unpublished content, while authors can only see their own unpublished content. Anonymous & authenticated users are unable to view any unpublished content.

**Comment by jpinsent** [comment]
Reopening. Basic page content is still hidden from every user role while unpublished, but News is functioning as intended. Relabelling this as a basic page issue.

**Comment by jpinsent** [comment]
Testing on AODA Demo. Currently, it looks like only the main admin and editors can view unpublished content. Users, site managers and authors are unable to view them and are taken to a '403 - Forbidden' page. Not sure if the site manager is supposed to be able to view unpublished content. Issue can be closed if this is working as intended.

Unpublished page: https://aoda.web.uoguelph.ca/aodademo/unpub-page
Unpublished event: https://aoda.web.uoguelph.ca/aodademo/unpub-event
Unpublished news: https://aoda.web.uoguelph.ca/aodademo/unpub-news

Use masquerade to switch between testuser (user), testauth (author), testeditor (editor), and testman (site manager).
