### ISSUE TITLE
PP5 - People Profiles listing page /people/tag/%tid and grid page /people/faces/%tid do not work with category tag ids

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#461]
Filter on people profiles listing and grid (faces) pages do not work with category tag ids. (It still works with keyword tag ids.)

For the moment, I'll be fixing the issue manually on sites that require this filter. When the fix is applied to the platform, the plan is to fix it in the same way so that the code matches up with the platform code when released.

**Method for fixing:**
1. Go into the PP5 and PP1B views
2. Under Contextual Filter, remove the "Content: Category" and "Content: Keyword" filters
3. Under Contextual Filter, select Add and search for the "Content: Has taxonomy term ID" filter.
4. Select Apply (all displays)
5. Configure contextual filter so "When the filter value is available or a default is provide:" check Override title and input "%1" as the value.
6. Select Apply (all displays)
7. Select Argument Input: Edit
8. Select "From panel argument" and Panel argument: "First"
9. Save each view.

**Addition:** This also affects the No Pictures version of the People Profiles filtered by tag.

**Comment by mmafe** [comment]
@abanuog will retest and create a pull request to merge onto master.

**Comment by mmafe** [comment]
Note: this also affects the No Pictures version of the listing page

**Comment by abanuog** [comment]
@mmafe Hi Miranda, the No Pictures version also was changed. Did you notice a problem  when testing something ?
