### ISSUE TITLE
E5 - Events Archive should be consistent with News Archive in terms of structure / styling

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#464]
News Archive (ie. Browse news by date) view pane appears in a select list.

![image](https://cloud.githubusercontent.com/assets/1927902/15659928/7a4df970-26a1-11e6-93ff-627491484400.png)

Events Archive view panes appears as the previous long list.

![image](https://cloud.githubusercontent.com/assets/1927902/15659924/65e05faa-26a1-11e6-992c-06634aec69ab.png)

Recommend updating Events Archive to be consistent with News.

**Comment by mmafe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) #464 Events archive](https://trello.com/c/uKa4hQHc/2024-5-464-events-archive)

**Comment by ushenoyuog** [comment]
Closing issue as it seems to merged into master
