### ISSUE TITLE
Include screen-reader-only descriptive text & button styling for more link on Feeds Aggregator

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#467]
Include screen-reader only descriptive text with the Drupal feed aggregator more link that references the title of the feed. This may involve overriding the template for the feed aggregator.

eg. Although the link would say "More," a person using assistive tech would hear "More Department News" if the title of the feed is Department News.

Also suggest adding styling for the link while updating the text (class="btn btn-default")

**Comment by mmafe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tNYnC3Fx&#x2F;1509-fix-issue-456-broken-attachment-on-profile-migration-0-5"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Fix Issue 456 - broken attachment on Profile migration [0.5]</a>

**Comment by brharp** [comment]
Override the theme function for aggregator blocks.
- Add feed title to "More" link as screen reader text.
- Add button classes to "More" button.
- Generally format aggregator block to resemble news teaser.

**Comment by mmafe** [comment]
Added to Kanban board

**Comment by mmafe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unit Test - Issue 467](https://trello.com/c/s36Cze3M/1894-unit-test-issue-467)
