### ISSUE TITLE
UG Migrate D7 - Allow default values to be set for categories in the migrate settings file

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#468]
For multiple migrations, we typically set the category field manually in the database.

Instead, suggest allowing default values to be set by for taxonomies in the migrate settings file

We may still have to manually add each row to the taxonomy_index.

**Comment by chyatt** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7sTOgqNh&#x2F;1506-2-fixed-issue-468-allow-migrator-to-set-default-values-for-taxonomies-during-migration-this-should-help-with-multiple-migrations"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (2) Fixed Issue 468 (Allow migrator to set default values for taxonomies during migration -- this should help with multiple migrations) [2]</a>
