### ISSUE TITLE
WF - Captcha Math question (ie. 10+9) is not being read out by screen-reader in forms/focus mode

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#493]
The Captcha Math question is not being read out by my screen-reader in forms/focus mode (ie. when I'm tabbing around the page). 

The label "Math question (required)" is read out, however the math question itself is outside the label and not connected by aria (or any other method that would let me read the question while in Forms mode).

Tested with both NVDA/Chrome and NVDA/Firefox.

![image](https://cloud.githubusercontent.com/assets/1927902/16806361/359fbf94-48e2-11e6-8d33-3830ae080fdb.png)

**Screen reader Output while tabbing in focus/forms mode**
```
First Name  edit
blank
Last Name  edit
blank
Math question (required)  edit
blank
Submit
button
```

Note: If I were to start at the top of the page and read through the whole page in browse/virtual mode, I could pick up the math question, however, this is a form and most people navigating the form will be using Forms mode.

**Comment by mmafe** [comment]
May just require installation of Recaptcha

**Comment by mmafe** [comment]
Documentation will also be available for this regarding how to use, so clients will know the Recaptcha is the more accessible.

**Comment by mmafe** [comment]
For future reference, this is referring to the version of reCaptcha where users have to click "I'm not a robot"

**Comment by brharp** [comment]
Won't fix; we will use Google reCaptcha instead. Sites that have this problem can be switched over to use recaptcha.
