### ISSUE TITLE
CO - Course Outlines detail page should hide field label if no associated content exists (eg. Term, Instructor)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#494]
Course Outlines detail page should hide field label if no associated content exists (eg. Term, Instructor).

![image](https://cloud.githubusercontent.com/assets/1927902/16840813/a96b7be4-49a4-11e6-9f95-8229b35be335.png)

**Comment by brharp** [comment]
Please commit fix to #579

**Comment by bdavey07** [comment]
http://iss494-bdavey.c9users.io/
