### ISSUE TITLE
CO - Request to move Academic Level and Subject filter to the Course Outlines listing page pane configuration

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#496]
Request to move Academic Level  to the Course Outlines listing page pane configuration.

Also to explore allowing either (a) the subject to be specified in the URL or if not possible, (b) moving the Subject filter into the pane config.

When configuring site, the idea will be for users to use the menu to navigate to a graduate course or a particular subject, as opposed to filtering a listing table.

**Comment by mmafe** [comment]
After discussion, this change will likely need "Level" to be set to required.

**Comment by brharp** [comment]
Fixed in 7.7.0
