### ISSUE TITLE
CO1 - When filtered by term (ie. semester), Course Outlines listing page title does not change.

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#500]
When filtered by term (ie. semester), Course Outlines listing page title does not change.

**Course Outlines page**
![image](https://cloud.githubusercontent.com/assets/1927902/16854916/0f97715c-49e1-11e6-9775-3a4a9ae7fac4.png)

**Winter 2015 Course Outlines page**
![image](https://cloud.githubusercontent.com/assets/1927902/16854936/2001d870-49e1-11e6-89d4-af9e3ab29985.png)

**Comment by brharp** [comment]
We changed this to only filter by tag id or course outline category id.
