### ISSUE TITLE
PP1 No Pictures - Role filter does not work on submit

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#507]
On the PP1 No Pictures view pane, the role filter does not work when submitted. Instead of going to sitename/people?field_profile_role_tid=#, it goes to sitename?field_profile_role_tid=#.

Needed for Business client site.

**Comment by tqureshi-uog** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;UAAd5G3D&#x2F;1803-add-140-faces-grid-view-to-people-profiles-along-with-other-people-profile-fixes"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add 140 Faces grid view to People Profiles along with other People Profile fixes</a>

**Comment by tqureshi-uog** [comment]
@mmafe Is this already fixed? When I go to https://www.uoguelph.ca/business/people?field_profile_role_tid=46 the role filters work properly

**Comment by mmafe** [comment]
@tqureshi-uog As far as I can tell, this has not been fixed on the AODA platform.

It looks like it was fixed manually on Business (see https://www.uoguelph.ca/business/admin/structure/features/ug_profile/diff/views_view)

**Comment by brharp** [comment]
This may be fixed by William’s pull request:

https://github.com/ccswbs/hjckrrh/pull/524/commits/b6f068ce514cac7dad68decc05db4b549526ad5b

**Comment by brharp** [comment]
Please test William’s branch and see if it fixes the problem.

**Comment by tqureshi-uog** [comment]
William's fix worked, now merged with Master
