### ISSUE TITLE
PP0 - Request to change "Lab" to "Room" for field label

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#508]
There's been a request to update the label on Lab to Room on the Business site. Is this something that would be worth changing on the platform?

Alternatively, we could just override it on the Business site, but I would not want to do this if there are negative effects in future as a result.

**Comment by tqureshi-uog** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;UAAd5G3D&#x2F;1803-create-generic-version-of-140-faces-and-turn-it-into-feature-for-aoda-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Create generic version of 140 faces and turn it into feature for AODA theme</a>

**Comment by mmafe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#604 - People Profiles listing - add Office](https://trello.com/c/Cf90LcW4/2104-604-people-profiles-listing-add-office)

**Comment by mmafe** [comment]
Solved by https://github.com/ccswbs/hjckrrh/issues/624
