### ISSUE TITLE
Breadcrumb depends on path alias

### ISSUE THREAD

**Issue by brharp** [ccswbs/hjckrrh#513]
Path breadcrumbs don't work for some news articles, events, etc.

Breadcrumbs depend on the path. For example, news articles with a path alias like "news/[node:title]" get the "News" breadcrumb as expected. News articles with a path like "node/1234" don't.

Path breadcrumb is configured to select a breadcrumb configuration based on the path, not the content type of the node.

Change the path breadcrumb configuration to use the "Node: type" selector rather than the path selector.

**Comment by nevantan** [comment]
Verify is fixed and write functional test.

**Comment by bdavey07** [comment]
This issue seems to be fixed, test exists https://github.com/ccswbs/testing/pull/8

**Comment by bdavey07** [comment]
http://iss513-bdavey.c9users.io/

**Comment by bdavey07** [comment]
![screenshot 2017-04-21 at 2 06 44 pm](https://cloud.githubusercontent.com/assets/24195670/25290388/dbd8749a-269b-11e7-8f77-36a90f3aa43e.png)
![screenshot 2017-04-21 at 2 06 42 pm](https://cloud.githubusercontent.com/assets/24195670/25290385/dbd38e08-269b-11e7-94fb-fe9726ec26d6.png)
![screenshot 2017-04-21 at 2 06 40 pm](https://cloud.githubusercontent.com/assets/24195670/25290387/dbd7cc52-269b-11e7-9d0c-bc1f9ec371f7.png)
![screenshot 2017-04-21 at 2 06 37 pm](https://cloud.githubusercontent.com/assets/24195670/25290386/dbd616f0-269b-11e7-8fd1-a7ba7d77e730.png)

**Comment by bdavey07** [comment]
Fixed
