### ISSUE TITLE
PP1 (No Pictures) - Position/Title is missing from People Profiles listing page (no pictures)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#514]
Please add the position/title to the People Profile listing view/pane with No Pictures. This pane and its corresponding view are meant to mirror the People Profile listing version with Pictures, which has the position/title.

Note that client (Business) is planning to use this version on their site, so it would be ideal if we could fix this prior to their going live.

**Comment by mmafe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PA4rR0uj&#x2F;1731-5-business-follow-up-profile-fixes"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (5) Business Follow-up Profile Fixes</a>

**Comment by tqureshi-uog** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;UAAd5G3D&#x2F;1803-create-generic-version-of-140-faces-and-turn-it-into-feature-for-aoda-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Create generic version of 140 faces and turn it into feature for AODA theme</a>

**Comment by mmafe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unit Test - Issue 514](https://trello.com/c/h7KLtC0B/1895-unit-test-issue-514)
