### ISSUE TITLE
E1 - Upcoming Events listing filtered by category does not work (No events show)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#520]
Attempting to filter events by category using https://aoda-web.uoguelph.ca/business/events/upcoming/[category ID]

**Current Result:** No events filtered by that particular category (110 - Business Career Development Centre) show. Ensured there were both past and future events in the category while testing.

![image](https://cloud.githubusercontent.com/assets/1927902/17865009/8044dc18-686e-11e6-8fd7-121a6d05b465.png)

Preferred result would be for users to be able to see a listing of events (upcoming) filtered by a category, and for the page title to reflect that category for accessibility purposes. This might require a view that shows all events of a category as opposed to just upcoming or past.

**Comment by brharp** [comment]
Fixed by #547.
