### ISSUE TITLE
No Picture Version of PP1 redirects to home when filtered

### ISSUE THREAD

**Issue by whazell** [ccswbs/hjckrrh#523]
When the No Picture version of PP1 is used, filtering on the listing page causes a redirect to the home page, instead of filtering.

Fix:
Structure>Views>Displays>No Pictures>Pane Settings>Use Panel Path = Yes 

Default is currently "No"

**Comment by mmafe** [comment]
Identical issue to https://github.com/ccswbs/hjckrrh/issues/507
