### ISSUE TITLE
S3 - Add snapchat to the list of available social media types

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#528]
Request from Business to add snapchat to available social media types.

---

## Update (Mar 27, 2017)
- IB also asked for this

**Comment by chyatt** [comment]
Is flickr available? I'm thinking of the United Way footer.

C

**Comment by mmafe** [comment]
Yup - Flickr is available.

**Comment by nevantan** [comment]
I refuse to add Snapchat on principle.

**Comment by nevantan** [comment]
An icon could be added to the social module as a "follow us" link. The client can set any URL they want and we can recommend they link to a basic page with their Snapchat QR code. They can link the QR code to the Snapchat profile URL which will allow direct adding from a mobile device with Snapchat installed.

**Comment by mmafe** [comment]
I will do this work on the condition that @nevantan has to approve the pull request. ^_^

**Comment by nevantan** [comment]
Another note: recommend linking to https://www.snapchat.com/add/[snap_id] rather than basic page.

**Comment by ushenoyuog** [comment]
Closing because pull request is approved.
