### ISSUE TITLE
Update platform documentation to include how to use blocks effectively

### ISSUE THREAD

**Issue by brharp** [ccswbs/hjckrrh#538]
Please speak to the AODA team to understand the problem(s) users are trying to solve, and document solutions to them so they can be solved in a self-serve manner going forward. This should be added to Margaret's training materials.

One example: Math & Stats wants an image in the sidebar here: https://aoda-client.uoguelph.ca/mathstat/feature/puzzles

**Comment by brharp** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bhXH8rjG&#x2F;1947-update-platform-documentation-to-include-how-to-use-blocks-effectively"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update platform documentation to include how to use blocks effectively</a>

**Comment by NicholasMacedo** [comment]
Done 
Can be viewed at https://ccswbs.gitbooks.io/uog-drupal-training/content/features/howto-blocks.html

**Comment by chyatt** [comment]
Thank you @NicholasMacedo, this is an excellent how-to!

I would also like to see a description and some examples to help flesh this out. E.g. What are 3-5 common use cases for this functionality, and how do you accomplish those use cases?

What do you think?

**Comment by NicholasMacedo** [comment]
Documentation updated with examples.

**Comment by chyatt** [comment]
Thanks @NicholasMacedo!
