### ISSUE TITLE
G0 - Listing pages theme - spacing between items

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#54]
For the listing pages themes, there will need to be some more spacing between the elements or some kind of horizontal seperator. Currently it is hard to determine where one end and the next starts, especially if the summaries are different sizes or there isnt a featured item.

**Comment by mmafe** [comment]
Solved on News listing page. Once we have a class that's only specific to listing pages, we'll add the class across Events, Featured Item, People Profiles, Services, etc.

**Comment by mmafe** [comment]
This issue has been resolved across all listing pages.
