### ISSUE TITLE
500 error accessing admin/config URL

### ISSUE THREAD

**Issue by brharp** [ccswbs/hjckrrh#541]
After updating to the latest version of master, some sites throw a 500 error when accessing the Configuration page.
```
[Wed Sep 21 13:15:02 2016] [error] [client 131.104.93.93] PHP Fatal error:  Call to undefined function bootstrap_include() in /var/www/drupal/profiles/ug/themes/ug/ug_theme/template.php on line 8, referer: https://dev.web.uoguelph.ca/ccs/
```

**Comment by brharp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/ZwwO732d/2021-test)

**Comment by brharp** [comment]
Workaround: Enable bootstrap theme.

**Comment by tqureshi-uog** [comment]
Release Notes have been updated. Bootstrap theme enabled by default in new installations, so no changes to make. Just fix the problem on an ad-hoc basis if it comes up again on older sites.
