### ISSUE TITLE
Find Ckeditor method of aligning elements (right, left, center) that does not use style attribute

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#567]
This relates to Issue #566.

WCAG 2.0 recommends that users [separate information and structure from presentation to enable different presentations](https://www.w3.org/TR/WCAG20-TECHS/G140.html). Because of this, whenever the AODA team does Accessibility Reports, we recommend clients avoid using the HTML style attribute to style their content, and instead use CSS.

In the case of images, if we use right align button on an image, images are floated right using the style attribute. It would be preferable if right aligned images in CKEditor used CSS to right align images instead of the style attribute.

CKEditor 

![image](https://cloud.githubusercontent.com/assets/1927902/19743876/1ae5664a-9b99-11e6-920a-aba57d25288a.png)

![image](https://cloud.githubusercontent.com/assets/1927902/19743896/2a45eaec-9b99-11e6-9769-ad35eac30f6d.png)

![image](https://cloud.githubusercontent.com/assets/1927902/19743912/386a770a-9b99-11e6-9346-7818ed4ff037.png)

**Comment by tqureshi-uog** [comment]
Could not find a way to change the behavior of the alignment buttons (by default, they assign classes to paragraph text but inline styles to images)

Instead, added the *Styles* dropdown menu to both Filtered and Full HTML toolbars, and updated ckeditor.styles.js to:

- provide pull-right and pull-left bootstrap classes to image elements
- remove Align, HSpace and VSpace fields from Image Properties dialog
- also provide the following new classes: pr-padding, pl-padding, and pull-center (the first two are automatically assigned depending on whether a user chooses to right or left-align an image)

Also updated base.css and CKeditor filter settings to include the new styles (pull-center, pr-padding, pl-padding)

**Comment by brharp** [comment]
Since this solution is quite a bit different from the original request, please check with Miranda to see if the proposed solution addresses the case she had in mind.

**Comment by brharp** [comment]
Is there a solution that uses existing bootstrap classes (e.g. `div.thumbnail`), rather than custom classes? I would like to limit our use of custom classes in favour of those provided by bootstrap.

**Comment by mmafe** [comment]
Note: Tanya and I reviewed her solution and it sounds like it fulfills what I was hoping for.

**Comment by brharp** [comment]
Style dropdown options will be "Image on Left", "Image on Right", "Image Centred". Selecting will apply the classes "pull-left gap-right", "pull-right gap-left", "center-block". The styles only apply to images. To remove the margins, remove the gap- classes using the advanced image properties.

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Find Ckeditor method of aligning elements (right, left, center) that does not use style attribute](https://trello.com/c/sPY0JENe/227-find-ckeditor-method-of-aligning-elements-right-left-center-that-does-not-use-style-attribute)

**Comment by mmafe** [comment]
Looks like this has been merged onto master. Closing.
