### ISSUE TITLE
S3/S4 - Missing icons for two options

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#57]
MySpace and Vimeo do not have visible icons associated with them. They appear in the social media directory with text, but without any icon next to them.
![social media](https://cloud.githubusercontent.com/assets/12450480/8256773/2e9013b4-1677-11e5-84e5-a7197f02ae89.PNG)

**Comment by jpinsent** [comment]
Just updating this issue. Due to the current view, these icons are now inaccessible. Publishing MySpace or Vimeo social media nodes causes an unclickable blank gap to appear (see the image below. Vimeo is supposed to appear between Pinterest and Youtube). Recommend getting rid of Vimeo and MySpace options or adding icons for them.
![social media 2](https://cloud.githubusercontent.com/assets/12450480/9525075/4ef9cb30-4cb0-11e5-914a-2a94bd0a6f2a.PNG)

**Comment by brharp** [comment]
Remove MySpace and Vimeo from list of social media options.

**Comment by ushenoyuog** [comment]
- [ ] test1
- [ ] test2

**Comment by ushenoyuog** [comment]
No Client is currently using either Vimeo or Myspace and unlikely that the would. Closing for now.
