### ISSUE TITLE
"Convert line breaks into HTML" filter inserts an extra <br> element which can cause validation issues on pages with <figure><figcaption>

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#570]
"Convert line breaks into HTML" filter inserts an extra break tag which can cause validation issues on pages with <figure><figcaption>.

Turning off the filter causes the validation issue to disappear.

Can we turn off this filter by default? Are there any reasons why we should leave the filter on as the default setting?

**Comment by nevantan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(0.5) #570 - "Convert line breaks into HTML" filter inserts an extra <br> element which can cause validation issues on pages with <figure><figcaption>](https://trello.com/c/QsGKNMWb/2152-0-5-570-convert-line-breaks-into-html-filter-inserts-an-extra-br-element-which-can-cause-validation-issues-on-pages-with-figure-)

**Comment by nevantan** [comment]
Filter already disabled by default.
