### ISSUE TITLE
Book outline menu broken / Trying to get property of non-object in node_page_title error showing after Bootstrap 7.x-3.8 update / affects all book pages

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#580]
The following issue appears to be affecting all book pages:

1. Shows Error: ```Notice: Trying to get property of non-object in node_page_title() (line 2200 of /modules/node/node.module).``` on each book page

2. Shows Outline button instead of the full book menu at the bottom of each book page.

Appears to relate to https://www.drupal.org/node/2034927

---

**Pre Bootstrap 7.x-3.8 update:** i.e. After checking out commit 4662bf0 Add tests for feed icon alt text (#549)

![book-pre-bootstrapupdate2](https://cloud.githubusercontent.com/assets/1927902/20204808/dafb0a80-a7a0-11e6-88bf-b5708a1cfbf0.png)
![book-pre-bootstrapupdate](https://cloud.githubusercontent.com/assets/1927902/20204810/e1ddfba0-a7a0-11e6-8113-d2c2d791299c.png)

**Post Bootstrap 7.x-3.8 update:** After checking out the latest branch on maint (ie. after the commit 652c798 Update: upgrade to Bootstrap version 7.x-3.8 ah)

![book-post-bootstrapupdate2](https://cloud.githubusercontent.com/assets/1927902/20204837/163fad3a-a7a1-11e6-85b1-e1a23bf7e387.png)

![book-post-bootstrapupdate](https://cloud.githubusercontent.com/assets/1927902/20204841/1e790578-a7a1-11e6-9dc4-c4cd495df2df.png)

Note: Issue is not showing up on the AODA dev sites at the moment. Looks like those sites have older code in the sites/all/themes/bootstrap folder than what's showing on github maint.

**Comment by brharp** [comment]
Fixed in 11.1
