### ISSUE TITLE
Events/Feed - Provide method to pull in events (ordered by event date) from other sites

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#583]
Provide method to pull in events from other sites. Events *must* be ordered by event date. 

CBS and CBE are interested in this for their production sites (i.e. their main site pulling in events from their department/academic unit sites). Currently they are able to use a feed to pull in these events, but they are ordered by post-date instead of event date.
![image](https://cloud.githubusercontent.com/assets/23462414/25281701/24feaf4c-267c-11e7-9893-91d417d40b7f.png)

**Comment by ushenoyuog** [comment]
## Acceptance Criteria

1. Feed must be ordered by event date 
2. Listing page must show event date /time and not post date/time
2. Ideally feed only pulls in upcoming events 
3. The events teaser and events listing page should look as much as possible like the normal 'events' content pages
![image](https://cloud.githubusercontent.com/assets/23462414/25281867/c1773038-267c-11e7-94fb-b2bf368ec60d.png)

**Comment by bdavey07** [comment]
The module [Date iCal](https://www.drupal.org/project/date_ical) provides a plugin for views that allows exporting a sites calendar as a iCal feed.  It also provides a plug in for Feeds that allows for importing an iCal feed into a sites calendar.  Could be set up to export from subsite calendars and import into main sites calendar.  Requires Views, Feeds, Entity API, Date and Libraries, all of which we already have and the [iCalcreator library](https://github.com/iCalcreator/iCalcreator).  

There are some well documented tutorials on how to implement this:

- http://websmiths.co/blog/drupal-7-feeds-tutorials-importing-ical
- https://cvanderlinden.com/web/drupal-7-installing-configuring-date-ical-work-events/
- https://www.slideshare.net/pvhee/importing-and-synchronizing-content-using-feeds
- https://www.drupal.org/node/1470996

**Comment by bdavey07** [comment]
Look into whether or not this is creating nodes in receiving sites.  Look into services achieving this

**Comment by bdavey07** [comment]
Another spike perhaps?

**Comment by tqureshi-uog** [comment]
Done
