### ISSUE TITLE
Ckeditor - Provide ckeditor users with style(s) to add margins around images

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#589]
**Situation:** Currently the only way that I've been able to find to add margins around images using Ckeditor is the Hspace / Vspace values. These add a style attribute which is something we're recommending clients avoid in order to separate their HTML structure from the CSS presentation (see [Nomensa's article on why inline styles are considered harmful for accessibility](https://www.nomensa.com/blog/2011/inline-styles-and-why-they-are-considered-harmful-accessibility).

**Request:** Recommend providing clients with a CSS style (or multiple styles) to add margins around images. Any provided styles must not use the HTML style attribute. It would be ideal if the style could be incorporated into the Ckeditor wysiwyg. Also if client documentation is updated so clients know how to add the style to an image.

An example of how this could be accomplished could be: creating a style called ```gap-right```which adds right margin of 10px; ```gap-left``` could add a left margin of 10px, etc.

-----

FYI This request originated from Footprints ticket #280249 (Kate Jenkins from Business requested method of laying images out horizontally on HFTM homepage. For that the ```pull-left``` and ```clearfix``` styles were recommended, however, the styles did not provide any spacing between the images. This meant the client was forced to add whitespace to the images so they would visually appear to have a margin.)

**Comment by brharp** [comment]
I don't buy the accessibility argument for margins. Using a class might be better for consistency and maintainability, but I wouldn't want to sink too much time into this issue.
For the specific example cited above, I would recommend a grid layout. To prevent the images from being scaled down, use col-md-6 or col-lg-6.

**Comment by mmafe** [comment]
Hey Brent,

I ended up doing some experiments at the time on https://aoda-client.uoguelph.ca/hftm/ and have recreated what I was finding below. Note that originally the client was looking to align 4 images horizontally, but since then, they seem to be using a grid of 4, so I've updated the experiments accordingly.

The main issue that I've been seeing is a too-wide gap between the two columns around the tablet-size view.  Is there a way to get around this?
![image](https://cloud.githubusercontent.com/assets/1927902/20679404/b3445bba-b568-11e6-9ddf-38b369e78bc3.png) 

I'm also finding that if I only use col-md-6 or col-lg-6, I end up with a vertical column of images below 992px, (see below under full experiments).

**Long story short:** We could recommend the grid layout and see if clients don't mind the additional whitespace that come as a result of the grid. I do have a few concerns regarding whether the solution may be too complex from the perspective of non-technical clients.

If we are recommending the grid, perhaps the focus should be updated to "Provide documentation for clients to layout content using the Bootstrap grid." Thoughts on this? Also are we intending to add the Bootstrap grid back into ckeditor for clients?

Re: accessibility of inline styles

I will agree that some inline styles definitely cause a larger accessibility barrier than other. I also think we cannot just assume that people using a different stylesheet for accessibility reasons will not want to change the margins on their images.

In general, we've been recommending that clients avoid all inline styles because of [G140: Separating information and structure from presentation to enable different presentations](https://www.w3.org/TR/WCAG-TECHS/G140.html). The description states "Structural encoding is the indication of elements such as headings, paragraphs, lists, tables, etc., and is done by using technology features reserved for the purpose. By contrast, presentational encoding is the indication of formatting effects, such as typeface, color, size, position, borders, etc., and is also supported by technology features." Given that description, I believe margins would definitely fit under presentational encoding, which if we're using this a11y technique, should be separated from the HTML.

Note: That was my attempt to gain your buy-in for avoiding inline styles for setting margins. ^_^

-----

# Full Experiments detailed below:

## Using col-lg-6 only

**Above 1200 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20678349/5b9d54b0-b564-11e6-92a1-b020fc0b914a.png)

**Below 1200 px **
![image](https://cloud.githubusercontent.com/assets/1927902/20678363/68161aa6-b564-11e6-932d-01910d54e339.png)

---------

## Using col-md-6 only
**Above 1200 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20678459/cecad318-b564-11e6-9c19-83c209196f3d.png)

**Above 992 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20678475/deb9ce1e-b564-11e6-8b2d-b8cff9c7258c.png)

**Below 992 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20678494/ef4db772-b564-11e6-901a-68e7b521f16b.png)

---------

## Using col-sm-6 only

**Above 768 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20678564/30ab517a-b565-11e6-88c8-a7f813c9c8f9.png)

**Below 768 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20678587/48318e54-b565-11e6-8535-b40c5d4046ac.png)

---------

## Using col-xs-6 only

**Above 1200 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20678639/7876557c-b565-11e6-9ba6-7384fc330de1.png)

**Below 768 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20678623/67e7ae68-b565-11e6-9ee3-b1e62873fd63.png)

![image](https://cloud.githubusercontent.com/assets/1927902/20678666/8faabbd4-b565-11e6-92e5-2232d0fa074d.png)

![image](https://cloud.githubusercontent.com/assets/1927902/20678673/977cfe4e-b565-11e6-8944-c2331d8bf243.png)

---------

## Best I was able to get -- Using col-xs-6 with col-lg-5 / col-lg-2

```
<div class="row">
<div class="col-xs-6 col-lg-5"><a href="#"><img alt="Logo test" class="img-responsive" src="https://dummyimage.com/125x125/c4c4c4/000000.png" /></a></div>

<div class="col-xs-6 col-lg-5"><img alt="Logo test" class="img-responsive" src="https://dummyimage.com/125x125/c4c4c4/000000.png" /></div>

<div class="col-lg-2">&nbsp;</div>
</div>

<div class="row">
<div class="col-xs-6 col-lg-5"><a href="#"><img alt="Logo test" class="img-responsive" src="https://dummyimage.com/125x125/c4c4c4/000000.png" /></a></div>

<div class="col-xs-6 col-lg-5"><img alt="Logo test" class="img-responsive" src="https://dummyimage.com/125x125/c4c4c4/000000.png" /></div>

<div class="col-lg-2">&nbsp;</div>
</div>
```

**Above 1200 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20679259/28f00004-b568-11e6-8fb2-4457771ff5ca.png)

**Above 992 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20679287/49a33db6-b568-11e6-8a1d-d0ff7fc594cc.png)

**Above 768 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20679313/60764c54-b568-11e6-86fd-552b79b9af4a.png)

**Below 768 px**
![image](https://cloud.githubusercontent.com/assets/1927902/20679321/6be6a386-b568-11e6-82af-e5ff40ce5b98.png)

![image](https://cloud.githubusercontent.com/assets/1927902/20679332/76463fe4-b568-11e6-92a9-e82fdff9dd09.png)

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ckeditor - Provide ckeditor users with style(s) to add margins around images #589](https://trello.com/c/yBoKuM8p/246-ckeditor-provide-ckeditor-users-with-style-s-to-add-margins-around-images-589)

**Comment by mmafe** [comment]
This may be solved by adding a paragraph around the images. You may need to double-check.

**Comment by mmafe** [comment]
Yes!

In order to get whitespace around an image, you can add a paragraph around the image:

```
<div class="row">
  <div class="col-xs-12 col-md-6">
    <p><img class="img-responsive" src=".." /></p>
  </div>
  <div class="col-xs-12 col-md-6">
    <p><img class="img-responsive" src=".." /></p></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-md-6">
  <p><img class="img-responsive" src=".." /></p>
  </div>

  <div class="col-xs-12 col-md-6">
    <p><img class="img-responsive" src=".." /></p>
  </div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/1927902/22904022/d1ac3b86-f208-11e6-922f-afb4a0ac17a6.png)
