### ISSUE TITLE
E1 - Events with start date in past and end date in future do not show up in Upcoming Events or Past Events

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#593]
It is currently possible for events not to show up in either Upcoming Events or Past Events if the start date is in the past and the end date is in the future. Events will still show up in This Week and Monthly Calendar.

Base requirement: It should show up in at least Upcoming Events.

------

Example below is from CSA Online.

Noticed on Thursday, December 1, 2016.

**Event Name:** [FoodBank Food Drive](https://csaonline.ca/foodbank-food-drive)
**Date and Time:** Monday, November 28th, 2016 9:00 AM to Friday, December 16th, 2016 12:00 PM
![image](https://cloud.githubusercontent.com/assets/1927902/20803974/22856a20-b7bf-11e6-891c-103afcb0d404.png)

**Upcoming Events:** Event does not show even though end date is in the future (Dec 16)
![image](https://cloud.githubusercontent.com/assets/1927902/20803906/df67691e-b7be-11e6-9c33-3a7ab3d94668.png)

**Past Events:** Event does not show because end date is in the future (Dec 16)
![image](https://cloud.githubusercontent.com/assets/1927902/20803925/efbdd01e-b7be-11e6-869f-69a5fd858e61.png)

**This Week:** Event shows in Week of November 27, 2016
![image](https://cloud.githubusercontent.com/assets/1927902/20803939/fdddc4b0-b7be-11e6-9bae-033054ea37ef.png)

**Monthly Calendar:** Event shows in month of December 2016
![image](https://cloud.githubusercontent.com/assets/1927902/20803950/0a1833a0-b7bf-11e6-9e4f-308a73892a5f.png)

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [E1 - Events with start date in past and end date in future do not show up in Upcoming Events or Past Events #593](https://trello.com/c/sIy0yEVG/243-e1-events-with-start-date-in-past-and-end-date-in-future-do-not-show-up-in-upcoming-events-or-past-events-593)

**Comment by nevantan** [comment]
## Ideal behavior
- Displayed in "Upcoming Events" as long as the end date is in the future
- Displayed in "Past Events" if the end date is in the past
- Displayed in "This Week" if the start date is before the end of the week or the end date is after the beginning of the week
- Displayed in "This Month" if the start date is before the end of the month or the end date is after the beginning of the month

## Steps taken
**E1 - Upcoming Events:**
1. Remove "Content: Date - start date" as a filter criteria
2. Add "Content: Date - end date" as a filter criteria
    - **Date selection form element:** Select
    - **Filter granularity:** Day
    - **Starting year:** -3 years from now
    - **Ending year:** +3 years from now
    - **Operator:** Is greater than or equal to
    - **First Section:** Enter a relative date, "now"
    - **Start date:** Enter a relative date, "now"
    - **End date:** [Default]

Everything else behaves correctly.

## Test Cases
**Note:** All tests assume a granularity of one day, meaning "in the past" is at least the day before the present day, and "in the future" is at least the day after. The present day covers a full 24 hours.

**Case 1:** Event starts and ends in past
**Expected Results:**
- Event displayed in "Past Events"
___
**Case 2:** Event starts and ends in future
**Expected Results:**
- Event displayed in "Upcoming Events"
___
**Case 3:** Event starts yesterday and ends tomorrow
**Expected Results:**
- Event displayed in "Upcoming Events"
- Event displayed in "This Week"
- Event displayed in "Monthly Calendar"
___
**Case 4:** Event starts in -8 days and ends in +8 days
**Expected Results:**
- Event displayed in "Upcoming Events"
- Event displayed in "This Week"
- Event displayed in "Monthly Calendar"
___
**Case 5:** Event starts in past and ends today
**Expected Results:**
- Event displayed in "Upcoming Events"
- Event displayed in "This Week"
- Event displayed in "Monthly Calendar"
___
**Case 6:** Event starts today and ends in future
**Expected Results:**
- Event displayed in "Upcoming Events"
- Event displayed in "This Week"
- Event displayed in "Monthly Calendar"
___
**Case 7:** Event starts today and ends today
**Expected Results:**
- Event displayed in "Upcoming Events"
- Event displayed in "This Week"
- Event displayed in "Monthly Calendar"
___
**Case 8:** Event starts -30 days and ends +30 days
**Expected Results:**
- Event displayed in "Upcoming Events"
- Event displayed in "This Week"
- Event displayed in "Monthly Calendar"

**Comment by ushenoyuog** [comment]
This is fixed. Closing Issue. New Issue #662 opened for teaser list.
