### ISSUE TITLE
People Profiles Listing - Add Last Name Search

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#594]
Request to make it easier to find people/browse in the people profile listing. This recently was discussed with COA, however other's might be interested in this as well (e.g. Business)

**Current Process for finding a person**
1. Navigate to /people
2. Scroll down, press next until you find the person

*Cons:* Process is not very efficient for multiple pages of people. Anyone whose last name starts with a letter in the middle of the alphabet is difficult to find quickly.

**Suggestions:** May relate to https://github.com/ccswbs/hjckrrh/issues/586 however solving that issue may not make it easier to browse the listing in general. Other thoughts include making the rows shorter and fitting more people. Adding an A-Z index. Reviewing other institution directories and determining if their process is easier for users to use. 

Recommend discussing during a Github meeting to determine exact steps or solution.

**Comment by ushenoyuog** [comment]
As per the Profiles enhancemnets meeting we had on 23 Jan 2017, it was decided to implement a last name search functionality. 

![image](https://cloud.githubusercontent.com/assets/23462414/22346521/6ccacf50-e3d2-11e6-9033-d2daab52bb9d.png)

Acceptability Criteria

- Must not require minimum three characters - This way if a user could list ou all proferssors with last name startin with P for e.g.
- Ideally we would have only one button for the search by last name and role filter. (So if 'A' is typed for last name , and role dropdown is set o faculty , the page will list all faculty with last name starting with A) -See image 
However , if this is too much addiotional effort , having the last name search seperate from the role dropdown will also be acceptable.

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [P 60 People Profiles Listing - Add Last Name Search](https://trello.com/c/ocD6NWQ0/233-p-60-people-profiles-listing-add-last-name-search)

**Comment by ushenoyuog** [comment]
Closing issue and pull request was merged and issue was accepted.
