### ISSUE TITLE
Enable courses (course outline) to have more than one attachment - by July 2017

### ISSUE THREAD

**Issue by ljairath** [ccswbs/hjckrrh#596]
FP#281279

Andrew (client) said that he does NOT need it until the Fall semester July 2017..Lalit

I am responsible for managing the department website for the Department of Mathematics and Statistics. We recently had the Course Outline feature activated, and it is terrific - very useful - thanks! Is it possible to add more than one file to a specific Course Outline instance? Some courses have more than one document to post, plus I believe this would be the easiest way to maintain an archive of course outlines (it is a lot of work to add a course, and I don't want to have to add 20-30 courses each semester - would be much easier to just post another course outline identified by the year).

Please let me know if this is currently possible, or whether I can request it to be added.

**Comment by ushenoyuog** [comment]
closing issue as it seems to be fixed.
