### ISSUE TITLE
People Profiles listing - add Office

### ISSUE THREAD

**Issue by tqureshi-uog** [ccswbs/hjckrrh#604]
The School of Computer Science would like the People listing - https://www.uoguelph.ca/computing/people - to show the Office Number field as well (currently it shows title, phone number, and email).

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [People Profiles listing - add Office](https://trello.com/c/Cf90LcW4/221-people-profiles-listing-add-office)

**Comment by ushenoyuog** [comment]
This is closed
