### ISSUE TITLE
In-Place Editor Add Content Overflows

### ISSUE THREAD

**Issue by nevantan** [ccswbs/hjckrrh#608]
The background of the in-place editor does not expand to fit content. Additionally, content that is taller than the max height will overflow the interface and not allow scrolling, potentially making some components inaccessible.

![add_content_bug](https://cloud.githubusercontent.com/assets/25013998/21908809/67551dea-d8e3-11e6-86c5-56dc7fffe691.png)

On sections with a number of elements, the content can overflow the screen and does not allow for scrolling, making elements near the bottom entirely inaccessible.

![content_overflow_no_scroll](https://cloud.githubusercontent.com/assets/25013998/22082473/dc24d596-dd95-11e6-89ea-8afd24517dff.png)

When the user has a small screen or are zoomed at all, some controls like the save button can be pushed off the screen. Similar to the previous case, this does not allow scrolling to access the button.

![zoom_save_button_inaccessible](https://cloud.githubusercontent.com/assets/25013998/22082523/17da61fa-dd96-11e6-8665-d014008966b7.png)

**Comment by nevantan** [comment]
Marked as high priority because this bug can create prevent some clients from being able to make changes entirely.

**Comment by nevantan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [In-Place Editor Add Content Overflows](https://trello.com/c/pxMtr4E6/2078-in-place-editor-add-content-overflows)

**Comment by nevantan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#608 - In-Place Editor Overflows](https://trello.com/c/W77IGD1j/2120-608-in-place-editor-overflows)

**Comment by ushenoyuog** [comment]
Closing issue since this is merged.
