### ISSUE TITLE
Add Meta Tags for Twitter Card Formatting

### ISSUE THREAD

**Issue by nevantan** [ccswbs/hjckrrh#610]
All pages need the meta tags described on the Twitter development site: https://dev.twitter.com/cards/types/summary

This is what the client is looking for (link to main UoG site - not a Drupal 7 site):
![ug_twitter_card](https://cloud.githubusercontent.com/assets/25013998/22065101/942ce1b6-dd54-11e6-8de3-a83059f240ad.png)

And this is what our Drupal 7 sites give (example link https://www.uoguelph.ca/police/news/2015/09/rental-scams-guelph):
![ug_twitter_card_fail](https://cloud.githubusercontent.com/assets/25013998/22065124/b82182b6-dd54-11e6-83bd-453ee0dd7095.png)

The meta tags should appear on every page so they will all auto-format when someone links to the site. 

News, events, and other content types with feature images can use that image in the meta tag. Other pages should default to the UoG logo.

**Comment by nevantan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Meta Tags for Twitter Card Formatting](https://trello.com/c/Gi9YwnG8/2079-add-meta-tags-for-twitter-card-formatting)

**Comment by ushenoyuog** [comment]
Closeing issue as all seems well and has been merged.
