### ISSUE TITLE
Book - Add default pathauto pattern for book pages

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#616]
Currently book pages end up with a URL alias that matches the default path pattern (```[node:menu-link:parents:join-path]/[node:title]```). Book pages aren't typically in the menu, so it can end up as ```[node:title]```.

Recommend updating the pattern to ```book-page/[node:title]```

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [P 35 Insufficient colour contrast/font-size on Event Grid](https://trello.com/c/hRGgbqNn/234-p-35-insufficient-colour-contrast-font-size-on-event-grid)

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#616 Book - Add default pathauto pattern for book pages](https://trello.com/c/Efop969L/257-616-book-add-default-pathauto-pattern-for-book-pages)
