### ISSUE TITLE
Images from Twitter should show up on the platform

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#618]
Currently images that are added to tweets on Twitter do not show up on on the Twitter feed on our Drupal platform. This is available on the old MCB platfrom , and hence they have requested us to find a way to have this on the new platfrom as well. 

## Image on Twitter 
![image](https://cloud.githubusercontent.com/assets/23462414/22441338/fe06c5c0-e704-11e6-8720-ac0608ab1347.png)

## On the Old MCB Platform (Image shows up)

![image](https://cloud.githubusercontent.com/assets/23462414/22441355/1046ae4e-e705-11e6-862b-322f6b24eb31.png)

## Image doesnt show up on Drupal platform 

![image](https://cloud.githubusercontent.com/assets/23462414/22441422/4f31e506-e705-11e6-910c-493fe9e30b25.png)

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Images from Twitter should show up on the platfrom. #618](https://trello.com/c/XzEsLJ0y/242-images-from-twitter-should-show-up-on-the-platfrom-618)

**Comment by nevantan** [comment]
The Twitter module we're using does not currently support images. There is an issue open on the project site (https://www.drupal.org/node/1981472) but it seems to be in a broken state at the moment.

**Comment by ushenoyuog** [comment]
This issue is being closed for the moment as it is something we do not want to pursue further at this point.
