### ISSUE TITLE
Allow Anchor in Filtered HTML

### ISSUE THREAD

**Issue by nevantan** [ccswbs/hjckrrh#621]
Allow anchor links in pages that use Filtered HTML. At present, a page must be set to Full HTML in order to include the necessary name/id attributes on anchor tags.

**Comment by nevantan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Allow anchor in Filtered HTML](https://trello.com/c/QElsPpCN/2101-1-allow-anchor-in-filtered-html)

**Comment by nevantan** [comment]
Updated filter in Configuration > Text Formats > Filtered HTML > WYSIWYG Filter to allow the id and name attributes on <a> tags.

The issue is that we need _both_ id and name in order for the link button to pick up an anchor for the dropdown. However, we cannot have the name attribute on the <a> tag because it is obsolete in HTML5.

If we do not allow the name attribute through the WYSIWYG Filter, CKEditor strips them between the database and the editor when a user goes to edit the page. This leaves the source without the name attribute and users cannot link to that anchor. 

By allowing the name attribute through the WYSIWYG Filter, it will appear on the page. We will need a custom filter to remove the attribute between the database and page while allowing it through to CKEditor.

Filtering Process:
**Save:** CKEditor -> Database
**Edit:** Database -> CKEditor Security Filters -> CKEditor
**View:** Database -> CKEditor Security Filters -> Drupal/Custom Filters -> Page

**Comment by ushenoyuog** [comment]
Closeing as it seems this fix was accepted and merged.
