### ISSUE TITLE
People Profiles : Customisable fields

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#624]
as discussed in the People profiles enhancements review meeting on 23 Jan 2017 : It was agreed to try and implement customisable fields for people profiles. 
Currently we have a few predefined fields that show up next to the image on the profile page. The customizable fields would be in addition to these fields. 

![image](https://cloud.githubusercontent.com/assets/23462414/22557109/6e89a5ae-e937-11e6-9dc6-4680ca12299a.png)

## Acceptance Criteria

1. Customisable fields can be added and deleted, for a particular site. They are in addition to the currently existsing fields. 
2.  The fields can be created, updated or deleted by a site manager. 
3. The field content can be updated by site manager, editor and author.
3. If the content of a field is blank it does not display
4.  The customisable fields are displayed below the regular fields , on the right side of the profile image.
5. Customised fields do not show up in the listing pages of profiles , and only appear on the details pages.

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Spike: Custom Fields](https://trello.com/c/hmPH8kAF/2105-1-spike-custom-fields)

**Comment by nevantan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#624 - Custom Fields](https://trello.com/c/mAirCiTW/2118-624-custom-fields)

**Comment by nevantan** [comment]
This functionality can be added by using field collections.
1. The fields added through collections are saved per page.
2. Site managers can control the available fields through Taxonomy
3. All roles can control visibility and content of fields by adding them to the field collection.
4. Fields can be omitted by removing them from the collection (or not adding them in the first place)
5. The field collection can be placed below the existing fields
6. Field collection fields will not show up on the listing page by default

**Comment by nevantan** [comment]
**Process:**
1. Add taxonomy for field labels
2. Add field collection to Profile content type
    - Ensure correct ordering
    - Allow unlimited fields

![add_field_collection](https://cloud.githubusercontent.com/assets/25013998/22656994/ec02ffde-ec62-11e6-8af4-5e8c7ea9b53d.png)

3. Remove Edit/Delete/Add links (for printer-friendly page)
4. Add fields to field collection
    - Check machine name
    - Check field display settings

![add_fields_to_collection](https://cloud.githubusercontent.com/assets/25013998/22659747/ddaafdce-ec6c-11e6-8885-f02e868a58ae.png)

5. Add field processing to profiles/ug/themes/ug_theme/template.php
6. Add CSS overrides to profile/ug/themes/ug/ug_theme/css/base.css
7. Export UG Personal profile feature

**Comment by mmafe** [comment]
Seems to have been merged into master. Closing the issue.
