### ISSUE TITLE
PP1 - Allow Site Managers to customize People Profiles listing page without overriding the ug_profile feature

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#625]
Allow Site Managers to customize People Profiles listing page without overriding the ug_profile feature.

**Requirements for listing page**
- Allow site manager to select size of displayed profile images (eg. thumbnail, medium)
- Allow site manager to choose *not* to display any profile images on the listing page
- If profile images are displayed, allow site manager to:
   - configure display so listing has a similar layout to the News Listing page (see Issue #471)
    - configure display so names are all vertically aligned for both users with pictures and without pictures
- Once site managers begin to make changes to the people profiles listing page, ensure the ug_profile feature is not put into a state of override by these changes.
- Ability to make these changes should be available to Site manager role only (not authors or editors).

Note: This issue can be modified once we learn more about what is possible given the above constraints.

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Spike: Customize Profile Display w/o Overriding UG People Feature](https://trello.com/c/CqhxsHCw/2106-1-spike-customize-profile-display-w-o-overriding-ug-people-feature)

**Comment by nevantan** [comment]
Fields can be added to views to function as variables that are then accessible from the template. PHP logic in the template itself can draw on the presence of "preset flags" to arrange itself into the desired layout.

Fields are added through Structure > Views > PP1 > No Pictures > Fields.

An example of a preset is the images. The template would have an if statement for each image size fields. If the field is present (ie. not null), the image is inserted into the template. Checking no image presets would result in no image, while checking multiple boxes would create multiple images. The intended use is for the user to check exactly zero or one boxes.

A template will need to be written or adapted to add this functionality.

Some customization options mentioned so far:
1. Image size
2. Text alignment with regard to image presence (if profile lacks image, move text to fill gap, or leave in line with text on profiles with an image)

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#625 PP1 - Allow Site Managers to customize People Profiles listing page without overriding the ug_profile feature](https://trello.com/c/4xCGwspb/241-625-pp1-allow-site-managers-to-customize-people-profiles-listing-page-without-overriding-the-ug-profile-feature)

**Comment by ushenoyuog** [comment]
Closing issue
