### ISSUE TITLE
N2 - Theme - Spacing of fields

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#64]
But some spacing between posting date, written by, and body field. Currently they look like they are all part of the same paragraph.

**Comment by mmafe** [comment]
Solved temporarily for News Detail page.

However, we still need a more generic class that we can use to roll out the style to all detail pages that have meta-data. For that reason, I'm leaving this issue open until we can space out the fields using that more generic (detail page) class.

**Comment by mmafe** [comment]
**Update:** This issue appears to have been solved. However, we've had feedback about the amount of space between the posted by date and written by fields.

Issue could be resolved by either decreasing the amount of space after the posted-by and written by fields OR consolidating the two fields into one field.

![screen shot 2015-08-07 at 3 46 46 pm](https://cloud.githubusercontent.com/assets/1927902/10282270/d69d574a-6b47-11e5-8f21-d21f39c8a08a.png)

**Comment by mmafe** [comment]
Ended up consolidating the fields into a single view n2ab. (Otherwise we'd have to limit the spacing between all panes on the page.)

![n2ab-screenshot](https://cloud.githubusercontent.com/assets/1927902/11601444/3dec8cc6-9aa1-11e5-9499-b3ef599ab5c7.png)

**Comment by jpinsent** [comment]
Testing in Chrome & FireFox on the Autobox. Lookin' good.

![news views test](https://cloud.githubusercontent.com/assets/12450480/11601922/a0c19b68-9aa4-11e5-8db0-c8833ec48b20.PNG)
