### ISSUE TITLE
%node_title in breadcrumb

### ISSUE THREAD

**Issue by brharp** [ccswbs/hjckrrh#643]
A few Drupal sites have reported seeing the text ‘%node_title’ in the breadcrumb links on certain types of content (notably news articles). 

Enabling the "UG Breadcrumb" (ug_breadcrumb) feature appears to fix the issue. The problem only occurs when the ug_path_breadcrumb module is enabled, and ug_breadcrumb is disabled.

**Comment by mmafe** [comment]
I was under the impression that ug_breadcrumb was a deprecated feature (I had worked on that one last year while trying to come up with a solution for breadcrumbs, but it was not ready to be used by production sites). In the end, we needed a different solution, which ended up being ug_path_breadcrumbs. However the ug_breadcrumb feature was never removed from the master branch. 

Given that ug_path_breadcrumb was meant to give breadcrumb functionality without relying on ug_breadcrumb, should we be relying on a feature that has not been tested (or meant to be used) on production sites?

**Comment by brharp** [comment]
ug_path_breadcrumb is the preferred option, but it doesn't appear to be working properly. For whatever reason, enabling ug_breadcrumb fixes the issue (as a workaround). I'm not saying that the final solution is to use ug_breadcrumb, I'm only pointing out that enabling the older features resolves the issue, which may be useful information when trying to track down the problem. I believe I missed the error when testing the ug_path_breadcrumb feature because the ug_breadcrumb feature "masks" the error if enabled.

**Comment by nevantan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) #643 - %node_title in breadcrumb](https://trello.com/c/7iASS4r9/2180-3-643-node-title-in-breadcrumb)

**Comment by mmafe** [comment]
**FYI:** It looks like enabling the UG Breadcrumb module enables the Crumbs module, which is what masks the error. If you disable UG Breadcrumb, the issue will still be fixed because Crumbs will still be enabled.

**Comment by tqureshi-uog** [comment]
See #677
