### ISSUE TITLE
Add Last name search to any views missing the feature (eg. Notable Alumni, PP6, PP5)

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#650]
We have last name search on the other profile views but we need to have it in the "faces" view that CBE uses for notable alumni.  https://www.uoguelph.ca/business/notable-alumni

The last name search issue was tackled in #594 . The functionality works exactly as that. 

![image](https://cloud.githubusercontent.com/assets/23462414/23711826/041f5b50-03ef-11e7-856d-2cb0b11a9ccc.png)

**Comment by bdavey07** [comment]
https://iss650b-bdavey.c9users.io/

**Comment by bdavey07** [comment]
PP5 is still broken, fix this

**Comment by bdavey07** [comment]
http://issues650-bdavey.c9users.io/
