### ISSUE TITLE
PP0 - Align Names field is showing on the edit profile/add new profile form (People Profiles)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#653]
![image](https://cloud.githubusercontent.com/assets/1927902/23802589/ce64423e-0581-11e7-884c-38b2130f4221.png)

This relates to Issue #625.

When editing existing profiles or adding a new profile, there is a checkbox related to the align names field showing at the bottom of the form. Since the checkbox has no effect in the context of the edit/create profile form, it would be preferable if we could not display the checkbox on this form.

**Comment by ushenoyuog** [comment]
Closing as pull request is approved. For any changes , please reopen.
