### ISSUE TITLE
Hide Exposed Filters on Views if either (a) no taxonomy terms exist OR (b) no nodes are tagged with any of the terms

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#655]
Hide Exposed Filters on Views if:
- no nodes are tagged with any of the terms
- no taxonomy terms exist in the filter

This is particularly relevant for People Profiles and can be tested using the Role filter on the People Profiles listing views (PP1, PP6, etc.)

- Catalyst Centre

**Comment by nevantan** [comment]
According to [this Views issue](https://www.drupal.org/node/256549), the Views module does not currently or plan to in future support hiding empty filters. Looked into two other modules that could potentially fix the issue:
[Views Selective Filters](https://www.drupal.org/project/views_selective_filters)
[Views Dependent Filters](https://www.drupal.org/project/views_dependent_filters)
but their use cases seem to be different and there didn't seem to be a way to make them work for our needs.

**Comment by nevantan** [comment]
It looks like we may have to override hook_form_alter or similar to achieve the effect we're looking for. See: http://drupal.stackexchange.com/questions/90502/how-to-hide-an-exposed-filter-block-if-the-view-results-are-empty for an example implementation.

**Comment by ushenoyuog** [comment]
Closing as pull request is approved. For any changes , please reopen.
