### ISSUE TITLE
Turn on "UG Responsive Tables" filter for Full HTML

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#673]
UG Responsive Tables (wraps tables with a bootstrap responsive class) is currently turned on for Filtered HTML, but not Full HTML.

Recommend turning the filter on by default for Full HTML under admin/config/content/formats/full_html

**Comment by ushenoyuog** [comment]
Closing as pull request is approved. For any changes , please reopen.

**Comment by mmafe** [comment]
@brharp: "I think this is a good change for Filtered HTML, but I don't think Full HTML should modify the markup in any way. If this was merged, we could not create an image without the responsive class, should the need arise."

I think this makes sense, so closing the unmerged pull request associated with this issue. (i.e. 
https://github.com/ccswbs/hjckrrh/pull/722)
