### ISSUE TITLE
Add Multi path autocomplete module to platform

### ISSUE THREAD

**Issue by tqureshi-uog** [ccswbs/hjckrrh#674]
This module - https://www.drupal.org/project/mpac - already happens to be installed on several servers (incl. ws-securehst15). Like the "internal link" feature in UG_wysiwyg, it allows you to find a node via keyword search when creating a new menu item (as opposed to having to know the node ID in advance and entering it manually)

It should be added to the theme and enabled by default. In-depth training on its use isn't really required since it functions like any other drop-down autocomplete field.

**Comment by nevantan** [comment]
Add to platform but not enable by default for now.
