### ISSUE TITLE
BR1 - Large image dimensions are not scaled properly

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#69]
I tried to upload a banner image of size 2000x1200. The image uploads fine with the message "The image was resized to fit within the maximum allowed dimensions of 1170x320 pixels."

When viewing the image on the banner, however, it does not display correctly. I believe the image is not being scaled correctly due to its dimensions.

The image being used looks like this:
![banner resize 2](https://cloud.githubusercontent.com/assets/12450480/8356711/e8a59ca4-1b24-11e5-8975-daf49361a150.PNG)

It is displayed on the banner like this:
![banner resize](https://cloud.githubusercontent.com/assets/12450480/8356709/e65f9d1e-1b24-11e5-921a-4fa769ed0e46.PNG)

**Comment by brharp** [comment]
Removing the maximum image resolution from the image field prevents image resizing (and the re-sized image is not used anyway).

**Comment by brharp** [comment]
Fixed in v7.5.0
