### ISSUE TITLE
PG0 - Content Type - Unrecoverable error occurred when attaching large file

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#7]
(I don't know if this is an intended error, or an actual error)

I attached a 34MB .jpg to the "File Attachments" on the basic page, when you press upload the system gives the following error in red:

"An unrecoverable error occurred. The uploaded file likely exceeded the maximum file size (20 MB) that this server supports."

it is unrecoverable since Drupal removes the option of uploading files until you either save the page as-is and re-edit it, or refresh the page and loose your progress.

**Comment by jszasz** [comment]
Update: If I update the 34mb .jpg, it gives the unrecoverable error.
With a 31mb .pdf, it gives you an error but still lets you try again

**Comment by JProxxi** [comment]
This issue is still present.
