### ISSUE TITLE
BR0 - Incorrect image size gives green check mark and red X

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#70]
![both errors](https://cloud.githubusercontent.com/assets/12450523/8357148/53d1f3ea-1b27-11e5-8448-1695a47a837d.PNG)

I uploaded an image where one demention was in the requirments and one dimention was not, and it gives both messages, that it worked and that it didnt work.

(Doesn't affect how it works, it's just the error messages)

**Comment by brharp** [comment]
Maximum resolution is being removed by #69, should no longer be an issue.
