### ISSUE TITLE
Front  End Performance testing

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#701]
<this issue may be converted into an epic if needed>

- Identify issues and areas of improvement 
-

**Comment by nevantan** [comment]
Just some initial points:
- Our current load times are approximately 4-5 seconds
- We can probably target ~2 seconds for load time
- Google's PageSpeed insights offers a number of useful tips: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.uoguelph.ca%2Fbusiness%2F&tab=mobile
- Images seem to be the biggest point, we would either need to educate uses on "saving for web" before they upload images, or offer an automated way to do so. See: https://www.drupal.org/project/imageapi_optimize
- Optimizing render-blocking resources is second on the list, see: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery and https://developers.google.com/speed/docs/insights/BlockingJS

**Comment by nevantan** [comment]
Potentially useful: http://www.hobo-web.co.uk/your-website-design-should-load-in-4-seconds/

**Comment by nevantan** [comment]
Look into AMP.

**Comment by bdavey07** [comment]
https://www.drupal.org/project/amp

**Comment by nevantan** [comment]
Document findings as we go with the intention of compiling them into a report.

**Comment by bdavey07** [comment]
http://yslow.org/

**Comment by bdavey07** [comment]
http://webresizer.com/resizer/

**Comment by bdavey07** [comment]
https://www.facebook.com/notes/facebook-engineering/bigpipe-pipelining-web-pages-for-high-performance/389414033919 awesome article on BigPipe Rendering

**Comment by bdavey07** [comment]
When running a page through [Google's PageSpeed Insights,](https://developers.google.com/speed/pagespeed/insights/ ) Google gives you a handy tool to download any optimized images, js or css for the page via a handy link at the bottom

**Comment by bdavey07** [comment]
https://www.drupal.org/project/advagg may assist with Javascript and CSS delivery

**Comment by bdavey07** [comment]
http://www.whatsmyip.org/http-compression-test/ tests compression on a R

**Comment by bdavey07** [comment]
https://developers.google.com/speed/pagespeed/module/

**Comment by bdavey07** [comment]
https://www.drupal.org/project/speedy

**Comment by nevantan** [comment]
https://www.npmjs.com/package/gpagespeed

**Comment by bdavey07** [comment]
- Do a prototype of current CCS website with performance optimisations applied
- Compile drupal 8 considerations
- Prepare a presentation for ccswbs/ccs all/spring IT day
- Look at running performance testing in testcafe

**Comment by bdavey07** [comment]
https://artillery.io/

**Comment by bdavey07** [comment]
https://artillery.io/docs/gettingstarted.html

**Comment by bdavey07** [comment]
Add to brand refresh doc: Ensure that we are rendering in the important content on the page first.

**Comment by bdavey07** [comment]
also amp
