### ISSUE TITLE
Search box/button alignment glitch

### ISSUE THREAD

**Issue by chyatt** [ccswbs/hjckrrh#720]
I noticed a tiny mismatch in alignment between the Drupal search box and button today. This shows up in production on at least the CCS and HR websites. See screenshot:

![search box glitch](https://cloud.githubusercontent.com/assets/804195/25195560/fddc2582-250b-11e7-84d9-7b092527b363.png)

**Comment by nevantan** [comment]
Affects all browsers on various zoom levels above 100%. I don't think there's anything we can do about this.

**Comment by chyatt** [comment]
I can live with the decision, though I'd like to see the reasoning documented and explained here a little bit so we can remember how we came to it in the future.

**Comment by nevantan** [comment]
Dealing with alignment like this across different browsers at different zoom levels seems to require quite a bit of fiddling to get just right: http://stackoverflow.com/questions/6726135/css-exact-same-height-and-alignment-of-button-and-input-text-box.

As this search box is entirely Bootstrap-based, we would have to override the base styles and then deal with fiddling for the proper alignment. I don't know that this is worth the effort for something that does not occur on a majority of (browser/zoom) configurations.

Anyone else have further thoughts?
