### ISSUE TITLE
Bootstrap collapsible elements do not degrade gracefully

### ISSUE THREAD

**Issue by nevantan** [ccswbs/hjckrrh#732]
Bootstrap-based collapsible elements cannot be opened if Javascript is disabled or otherwise unavailable. Since the containers default closed, this makes the content within the collapsed area inaccessible (in the sense that no one is able to access the content, not that it is an accessibility issue).

Examples:
- https://dev.web.uoguelph.ca/tqdev/collapse
- https://www.uoguelph.ca/graduatestudies/future/applying-guelph

Proposed solution is to rely on a Javascript-based implementation, but defaulting collapsible sections to open.

**Comment by tqureshi-uog** [comment]
One of the solutions here appears to work: http://stackoverflow.com/questions/32889197/a-fallback-for-bootstraps-collapse-behaviour-when-js-disabled

Specifically, Option 2 to make use of the `noscript` tag:

`<noscript>
    <style>
        .collapse {
            display: block;
        }
              </style>
            </noscript>`

Just tested this on https://dev.web.uoguelph.ca/tqdev/collapse and it appears to work (and is accepted by CKeditor Filtered HTML mode)

**Comment by tqureshi-uog** [comment]
After discussion with @mmafe it was determined to add this code snippet to https://github.com/ccswbs/hjckrrh/blob/master/profiles/ug/themes/ug/ug_cornerstone/templates/html.tpl.php - I'm going to go ahead and create a pull request based on this and make it available for testing

**Comment by ljairath** [comment]
Please notify the clients once this issue is resolved. These are the two clients that I know of requesting for the feature. Add client to the following list if requested. 
 
Steve Forbes: FP #292387 Re: Drupal question Ticket closed.
Renee Shea: FP #290521 Re: question abour restructuring our HR Contacts Page
