### ISSUE TITLE
Finish CCS Optimization Presentation and Review

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#746]
Refer #701 

- [x]  Make a prototype of current CCS website with performance optimisations applied
- [x]  Prepare a presentation for ccswbs/ccs all/spring IT day

**Comment by bdavey07** [comment]
Created a site in the test environment on ws-securehst18 at https://aoda-test.web.uoguelph.ca/ccs/
Password is in KeePass (synchronize to see it)
Site is exact replica of live ccs site as of this morning's backup (Tuesday May 23, 2017)

**Comment by bdavey07** [comment]
**PDF Copies of PageSpeed Insights ran on both test and live sites today (23/05/2017)**
[insightsLiveDesktop05_23_17.pdf](https://github.com/ccswbs/hjckrrh/files/1023360/insightsLiveDesktop05_23_17.pdf)
[insightsLiveMobile05_23_17.pdf](https://github.com/ccswbs/hjckrrh/files/1023362/insightsLiveMobile05_23_17.pdf)
[insightsTestDesktop05_23_17.pdf](https://github.com/ccswbs/hjckrrh/files/1023363/insightsTestDesktop05_23_17.pdf)
[insightsTestMobile05_23_17.pdf](https://github.com/ccswbs/hjckrrh/files/1023361/insightsTestMobile05_23_17.pdf)

**Comment by bdavey07** [comment]
**PDF Copies of PageSpeed Insights ran EOD today (23/05/2017) on test site**
[insightsTestDesktop05_23_17.1.pdf](https://github.com/ccswbs/hjckrrh/files/1023641/insightsTestDesktop05_23_17.1.pdf)
[insightsTestMobile05_23_17.1.pdf](https://github.com/ccswbs/hjckrrh/files/1023642/insightsTestMobile05_23_17.1.pdf)

#### Changes made
- Banners replaced with automatically generated images by PageSpeed Insights

**Comment by nevantan** [comment]
Some additional benchmarks:
[live_gtmetrix.pdf](https://github.com/ccswbs/hjckrrh/files/1029761/live_gtmetrix.pdf)
[live_pingdom.pdf](https://github.com/ccswbs/hjckrrh/files/1029762/live_pingdom.pdf)
[live_webpagetest.pdf](https://github.com/ccswbs/hjckrrh/files/1029763/live_webpagetest.pdf)

**Comment by bdavey07** [comment]
Installed [Advagg Module](https://www.drupal.org/project/advagg)

**Comment by bdavey07** [comment]
**With manually optimized images and Advagg installed and configured**
[insightsTestDesktop06_02_17.pdf](https://github.com/ccswbs/hjckrrh/files/1047829/insightsTestDesktop06_02_17.pdf)
[insightsTestMobile06_02_17.pdf](https://github.com/ccswbs/hjckrrh/files/1047830/insightsTestMobile06_02_17.pdf)

**With non-optimized images and Advagg installed and configured**
[insightsTestMobile06_02_17.1.pdf](https://github.com/ccswbs/hjckrrh/files/1047831/insightsTestMobile06_02_17.1.pdf)
[insightsTestDesktop06_02_17.1.pdf](https://github.com/ccswbs/hjckrrh/files/1047833/insightsTestDesktop06_02_17.1.pdf)

**With Advagg off, images non-optimized (manually) and Image Optimize module on**
[insightsTestMobile06_02_17.2.pdf](https://github.com/ccswbs/hjckrrh/files/1047878/insightsTestMobile06_02_17.2.pdf)
[insightsTestDesktop06_02_17.2.pdf](https://github.com/ccswbs/hjckrrh/files/1047879/insightsTestDesktop06_02_17.2.pdf)

**With Advagg on and Image Optimize on**
[insightsTestMobile06_02_17.3.pdf](https://github.com/ccswbs/hjckrrh/files/1047880/insightsTestMobile06_02_17.3.pdf)
[insightsTestDesktop06_02_17.3.pdf](https://github.com/ccswbs/hjckrrh/files/1047881/insightsTestDesktop06_02_17.3.pdf)

**With Advagg off and ImageMagick on**
[insightsTestDesktop06_02_17.4.pdf](https://github.com/ccswbs/hjckrrh/files/1047882/insightsTestDesktop06_02_17.4.pdf)
[insightsTestMobile06_02_17.4.pdf](https://github.com/ccswbs/hjckrrh/files/1047883/insightsTestMobile06_02_17.4.pdf)

**Note:** Advagg has a lot of configuration options, I am sure that more time spent learning every in an out of the module would give us a better score.

**Note:** ImageMagick module is currently throwing an error message, working to fix it, expect this score to be better when fixed

**Comment by bdavey07** [comment]
Don't think that I am using the Advagg module to its full capacity yet.  Image optimize module gave great results, mainly for mobile, which is arguably the most important for front end performance optimization.

**Comment by bdavey07** [comment]
There are more options in the image optimize module as well, including a quality option, which could increase performance even more

**Comment by nevantan** [comment]
ImageMagick looks to be the way to go as far as image optimization goes. The jpegoptim library seems to be difficult to install, and the already-installed jpegtrans library is not very effective.

Once configured, the ImageMagick module will automatically transform any newly uploaded images. We'll have to run a command on the server to optimize existing images. The following command run in the `/sites/[site]/files` directory will convert all jpegs automatically:
`mogrify -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace RGB *.jpg`

**Comment by nevantan** [comment]
Following the instructions from (this stack exchange question)[https://drupal.stackexchange.com/questions/107311/eliminate-render-blocking-javascript-and-css-in-above-the-fold-content] greatly improved "First Meaningful Paint", but broken a ton of stuff on the site (some pages would be css-less, all Bootstrap scripts broke, etc.).

I ended up having to make the following changes:
- Uncheck "Resource hint src attributes found in the HTML content"
- Select "All but JavaScript Libraries" under "Move JS to the footer"
- Select "Link Stylesheet" under "Do not defer the first css file"

The settings above seem to allow the site to function normally while providing the following benchmark:
[4-stack_overflow-fix_bugs.pdf](https://github.com/ccswbs/hjckrrh/files/1069054/4-stack_overflow-fix_bugs.pdf)

**Comment by bdavey07** [comment]
Rough first draft of presentation
https://docs.google.com/a/uoguelph.ca/presentation/d/1oWSt0GGEBp0NZzstFbkb4wZpAC-cCnEb2pkWJZB3Vm8/edit?usp=sharing

**Comment by bdavey07** [comment]
https://docs.google.com/presentation/d/1ZFV4IcrtfgdPpXN_mfTGhnHAdbGqOKDSMaPxWSl1J2o/edit?usp=sharing

**Comment by bdavey07** [comment]
- Make a 3 pronged timeline
- Split up desktop and mobile
- CCS all language
- Timeline at end
- Side by side banner images optimized/unoptimized
- Remove the word confusion
- Explanation of metrics slides
- Add aggregation info (@nevantan)

**Comment by nevantan** [comment]
Must finish and get review from @chyatt this sprint.

**Comment by bdavey07** [comment]
Notes from meeting with @chyatt 

## General
- Will be presenting at team meeting tomorrow (July 12)
- Is interested in having this presented at all staff, focus on more technical aspects compared to all staff
- Is happy with presentation in current state, no changes needed at this time (will probably change after feedback from rest of team)

## Action Items
- Look into how the optimized images look on different displays (higher res)
- At a ccs all presentation, don't be too technical but be prepared to answer technical questions
- Look into different browser results
- May need to change slide template for CCS all
- Show off modules and configurations at team meeting

**Comment by nevantan** [comment]
**Note:** Google Lighthouse is *only* for Chrome. Even the NodeJS command line version forces the use of Chrome/Chromium.
