### ISSUE TITLE
Webform component descriptions have low contrast

### ISSUE THREAD

**Issue by morganrees9** [ccswbs/hjckrrh#751]
When components are added to a webform, users can also add a description: 
![description](https://cloud.githubusercontent.com/assets/25161107/26409526/c10c7b24-406e-11e7-923e-450bc16c6107.png)

When this description saves, it looks like this: 
![low contrast instructions](https://cloud.githubusercontent.com/assets/25161107/26409547/d11f74ee-406e-11e7-95c4-61095c2af21f.png)

The light grey on white has a contrast ratio of 2.7:1.

**Comment by mmafe** [comment]
Fixed by #870
