### ISSUE TITLE
SEDRD Alumni Profile Migration

### ISSUE THREAD

**Issue by morganrees9** [ccswbs/hjckrrh#765]
SEDRD [notable alumni profiles](https://www.uoguelph.ca/sedrd/notable-alumni?field_affiliation_tid=All&field_time_period_tid=All&field_last_name_value=) can be migrated automatically to the client site. 

The profiles have two pictures. Go with the smaller one from the faces view for the new profiles.

**Comment by bdavey07** [comment]
Migration is complete, used the smaller of the 2 images for the profile image.  All profiles have "Notable Alumni" as the category.  The time on campus was migrated to keywords (some profiles have multiples on the legacy site).  The affiliation appears to have been used at one point on legacy but no longer used. I set up empty terms under "Area of Research" on the client site matching the Affiliation terms on the legacy site.

**Comment by bdavey07** [comment]
Also as a bonus, added https://aoda-client.uoguelph.ca/sedrd/notable-alumni as a redirect to the filtered faces view.
