### ISSUE TITLE
Glyphicons have wrong colour

### ISSUE THREAD

**Issue by brharp** [ccswbs/hjckrrh#766]
Glyphicons on buttons (or links styled as buttons) have the wrong colour. For example, buttons on the CCS website have white text and grey icons:

![image](https://user-images.githubusercontent.com/2037405/27038476-240ac610-4f59-11e7-859c-0f4938aa7dd2.png)

Most likely cause is this CSS rule:
````
.main-container .glyphicon {
    color: #666666;
}
````
Removing/disabling this rule restores the correct icon colour.

**Comment by mmafe** [comment]
@brharp Hey Brent, are you taking care of this or did you want the AODA team to add this to an upcoming sprint?

**Comment by brharp** [comment]
Doesn’t matter, go ahead and work on it if you have the time.

Brent

**Comment by tqureshi-uog** [comment]
Issue fixed already
