### ISSUE TITLE
Grad Studies - Non Image Fixes

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#773]
- [x] Remove the email from students who have it displayed , and leave it as is on faculty profiles (46)
- [x] Move ‘How my research will improve life’ to above ‘Why I chose Guelph’..  (16 students)
- [x] Change the word to ‘Programs’ to ‘Program(s)'

**Comment by bdavey07** [comment]
Can use search and replace scanner for Program -> Program(s).

- If not already turned on, go to `/admin/modules` and search for scanner, turn it on
- Go to `Find Content`, select the `search and replace scanner` tab
- Go to settings and select all check boxes under `Fields that will be searched` except the field you are searching
    - might be `profile: field_profile_summary` or  `profile: field_profile_content`
- Click save configuration
- Go back to search and search for `Profiles`
- Ensure the search query has found the correct pages 
- Enter `Profile(s)` in the replace field and click replace
- Check the results to ensure it worked as expected
- If it fails, the undo tab is your friend
