### ISSUE TITLE
People Profiles - Enable description field for file attachments

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#776]
Enable description field for file attachments. Currently files attached to profiles show the exact filename (e.g. myfile_0001_whateverthenameis.txt) instead of a descriptive label for the file attachment.

Note that all other content types (i.e. News, Page, Events, etc.) have the description field enabled for their file attachments.

**Comment by ushenoyuog** [comment]
##Acceptance Criteria

Description field should look and function as it does for other content types 
![image](https://user-images.githubusercontent.com/23462414/27695320-89f17f3a-5cbc-11e7-97f8-8bdccc73f0d1.png)
