### ISSUE TITLE
Siteimprove Issue: There is no top level heading (H1) on the page -D7

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#794]
Same issue as #792

**Comment by nevantan** [comment]
This error doesn't seem to be appearing on the D7 theme. The SiteImprove browser extension doesn't report it, and inspecting the page reveals that the site title is an `<h1>`, thus satisfying the requirements.

**Comment by nevantan** [comment]
@bdavey07 Could you double-check this?

**Comment by bdavey07** [comment]
Checked the following list of sites (aggregated from KeePass entries under Drupal 7 (responsive theme)) with the SiteImprove extension.

- http://www.lib.uoguelph.ca/
- https://www.uoguelph.ca/finance/
- https://www.uoguelph.ca/accessibility/web/
- https://www.uoguelph.ca/brdc/
- https://www.uoguelph.ca/cip/
- https://www.uoguelph.ca/cps/
- https://www.uoguelph.ca/crc/dunfield/
- https://www.uoguelph.ca/diversity-human-rights/
- https://www.uoguelph.ca/eaccess/
- https://www.uoguelph.ca/fairdealing/
- https://www.uoguelph.ca/globaljustice/
- https://www.uoguelph.ca/mentalwellbeing/
- https://www.uoguelph.ca/omsconsulting/
- https://www.uoguelph.ca/realestate/
- https://www.uoguelph.ca/sessional_ta/
- https://www.uoguelph.ca/sexualviolence/

None of the sites gave this warning, checked the front page and a couple deeper pages on each site.
