### ISSUE TITLE
Check new delivery of site for bugs, performance, logo, ssl

### ISSUE THREAD

**Issue by bdavey07** [ccswbs/hjckrrh#800]
- [ ] Bugs 
- [ ] SSL (Check to see if calling https resources from http will cause mixed content warnings
- [ ] Logo 
- [ ] Performance

**Comment by ushenoyuog** [comment]
Issue moved to [ccswbs/aoda-tasks #174](https://github.com/ccswbs/aoda-tasks/issues/174) via [**ZenHub**](https://www.zenhub.com/)
