### ISSUE TITLE
E0 - Section preview shows edit/delete/add buttons; sometimes 404s

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#84]
When you preview an event page, the Edit, Delete and Add buttons show up next to each section in the preview. Not sure if this is intentional or not. Clicking these seems to work sporadically, as it often takes you to a 404 error.
![capture](https://cloud.githubusercontent.com/assets/12450480/8480392/571dbadc-20ab-11e5-8ff2-a454c1ee1e3e.PNG)

**Comment by ushenoyuog** [comment]
This doesnt seem to be happening anymore.  Closing issue for now.
![image](https://cloud.githubusercontent.com/assets/23462414/25010933/a5af3fba-2039-11e7-9024-48c90e43d3b3.png)
