### ISSUE TITLE
Landmarks: use proper ARIA landmarks for assistive technology

### ISSUE THREAD

**Issue by ljairath** [ccswbs/hjckrrh#861]
Bypass Blocks (2.4.1): Landmarks are logical and informative, Level A
The use of ARIA landmarks on a webpage can be very helpful for assistive technology users, as they clearly outline different sections of a webpage. Many users will also choose to browse a page by jumping to the different landmarks on the page, which saves a great deal of time. The same landmark should not be used for different sections of a page. This can be confusing or disorienting for a user when they hear several of the same
8
landmarks with no way to differentiate them. Also, important areas of the page, such as the search box should be in a landmark. Best practice says all content on pages should be within landmarks on the pages and that there should be a main landmark on every page.
All pages should have a main and footer landmark. When there are two landmarks with the same name, they should be distinguished from one another.

**Comment by mmafe** [comment]
# List of recommendations from the Siteimprove manual audit specific to the hjckrrh theme

Sites: UAIC / OAC

- There are two navigation landmarks, one for the main navigation of the site and one for the navigation menu for the UAIC. These should be clearly labeled, so screen reader users know the difference between the navigation areas. (There are two landmarks called navigation which should be more clearly labeled to help users understand that one is for the site navigation and the other is for the UAIC navigation.)
- There are also two banner landmarks which are not clearly labeled and there is no main or footer landmark.
- As a best practice, all content should be within landmarks on the page. As a best practice, all page content should be found within landmarks. A main landmark should be used.
- (OAC) The Home and Resources for Students links above the main content should be recognized as a breadcrumb region for screen reader users.
- (UAIC) The links for “Home” and “Future Students” should be recognized by screen readers as a breadcrumb link region.
