### ISSUE TITLE
N0 - No maximum height or width set for News Featured Image

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#89]
Maximum upload size should be Height (570 px) by Width (1140 px)

**Comment by jszasz** [comment]
It seems to allow any size of image, as long as it is above the minimum size, and under the file size requirements (20MB). It will add the img-responsive tag, and the image shrinks to fit under the maximum size. The user is never informed of this.

Please inform the user of the max size, or that the image is being shrunk.

**Comment by jpinsent** [comment]
This looks like it's been resolved on the develop branch. It looks like 1140x570 is the maximum upload requirement on the Feature Image for News detail pages.
