### ISSUE TITLE
Ensure RSS alt text for teaser lists (events/news/features/etc.) is updated when title is overridden

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#912]
Teaser lists with overridden titles do not update the alternative text for the associated RSS feed.

![image](https://user-images.githubusercontent.com/1927902/58190330-46670b00-7c8a-11e9-8721-cba258944f74.png)

**Comment by dw235** [comment]
Solved: https://github.com/ccswbs/hjckrrh/commit/bd41a2153ec129221d3576aed7f3a5c790da5148
