### ISSUE TITLE
G1/F2 - View doesn't show breadcrumbs back to Category

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#96]
There is nothing on this view that is linking it back to the Category it belongs to. Miranda said that it should be listed in the breadcrumbs.

**Comment by mmafe** [comment]
For an example, FAQ details pages to show category (if applicable) like so:

*Home / FAQ / FAQ Category (if applicable)*

**Comment by Dmelady** [comment]
Ann asked that you have a plan to do this through page details etc. Thanks

**Comment by mmafe** [comment]
Refer to https://github.com/ccswbs/hjckrrh/issues/113

**Comment by mmafe** [comment]
Closed as duplicate.
